// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module main_design_v_mix_0_0_AXIvideo2MultiPixStream_5 (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        s_axis_video1_TDATA,
        s_axis_video1_TVALID,
        s_axis_video1_TREADY,
        s_axis_video1_TKEEP,
        s_axis_video1_TSTRB,
        s_axis_video1_TUSER,
        s_axis_video1_TLAST,
        s_axis_video1_TID,
        s_axis_video1_TDEST,
        srcLayer1_din,
        srcLayer1_num_data_valid,
        srcLayer1_fifo_cap,
        srcLayer1_full_n,
        srcLayer1_write,
        HwReg_layerHeight_1_val,
        HwReg_layerWidth_1_val,
        HwReg_layerEnableFlag_1_val,
        HwReg_layerEnableFlag_1_val_c17_din,
        HwReg_layerEnableFlag_1_val_c17_num_data_valid,
        HwReg_layerEnableFlag_1_val_c17_fifo_cap,
        HwReg_layerEnableFlag_1_val_c17_full_n,
        HwReg_layerEnableFlag_1_val_c17_write,
        HwReg_layerWidth_1_val_c24_din,
        HwReg_layerWidth_1_val_c24_num_data_valid,
        HwReg_layerWidth_1_val_c24_fifo_cap,
        HwReg_layerWidth_1_val_c24_full_n,
        HwReg_layerWidth_1_val_c24_write,
        HwReg_layerHeight_1_val_c32_din,
        HwReg_layerHeight_1_val_c32_num_data_valid,
        HwReg_layerHeight_1_val_c32_fifo_cap,
        HwReg_layerHeight_1_val_c32_full_n,
        HwReg_layerHeight_1_val_c32_write
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_state3 = 10'd4;
parameter    ap_ST_fsm_state4 = 10'd8;
parameter    ap_ST_fsm_state5 = 10'd16;
parameter    ap_ST_fsm_state6 = 10'd32;
parameter    ap_ST_fsm_state7 = 10'd64;
parameter    ap_ST_fsm_state8 = 10'd128;
parameter    ap_ST_fsm_state9 = 10'd256;
parameter    ap_ST_fsm_state10 = 10'd512;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [23:0] s_axis_video1_TDATA;
input   s_axis_video1_TVALID;
output   s_axis_video1_TREADY;
input  [2:0] s_axis_video1_TKEEP;
input  [2:0] s_axis_video1_TSTRB;
input  [0:0] s_axis_video1_TUSER;
input  [0:0] s_axis_video1_TLAST;
input  [0:0] s_axis_video1_TID;
input  [0:0] s_axis_video1_TDEST;
output  [23:0] srcLayer1_din;
input  [2:0] srcLayer1_num_data_valid;
input  [2:0] srcLayer1_fifo_cap;
input   srcLayer1_full_n;
output   srcLayer1_write;
input  [15:0] HwReg_layerHeight_1_val;
input  [15:0] HwReg_layerWidth_1_val;
input  [0:0] HwReg_layerEnableFlag_1_val;
output  [0:0] HwReg_layerEnableFlag_1_val_c17_din;
input  [2:0] HwReg_layerEnableFlag_1_val_c17_num_data_valid;
input  [2:0] HwReg_layerEnableFlag_1_val_c17_fifo_cap;
input   HwReg_layerEnableFlag_1_val_c17_full_n;
output   HwReg_layerEnableFlag_1_val_c17_write;
output  [15:0] HwReg_layerWidth_1_val_c24_din;
input  [2:0] HwReg_layerWidth_1_val_c24_num_data_valid;
input  [2:0] HwReg_layerWidth_1_val_c24_fifo_cap;
input   HwReg_layerWidth_1_val_c24_full_n;
output   HwReg_layerWidth_1_val_c24_write;
output  [15:0] HwReg_layerHeight_1_val_c32_din;
input  [2:0] HwReg_layerHeight_1_val_c32_num_data_valid;
input  [2:0] HwReg_layerHeight_1_val_c32_fifo_cap;
input   HwReg_layerHeight_1_val_c32_full_n;
output   HwReg_layerHeight_1_val_c32_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg s_axis_video1_TREADY;
reg srcLayer1_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    HwReg_layerEnableFlag_1_val_c17_blk_n;
reg    HwReg_layerWidth_1_val_c24_blk_n;
reg    HwReg_layerHeight_1_val_c32_blk_n;
wire   [0:0] HwReg_layerEnableFlag_1_val_read_read_fu_116_p2;
reg    ap_block_state1;
wire   [11:0] grp_reg_unsigned_short_s_fu_259_ap_return;
reg   [11:0] rows_reg_365;
wire    ap_CS_fsm_state2;
wire   [11:0] grp_reg_unsigned_short_s_fu_265_ap_return;
reg   [11:0] cols_reg_370;
wire   [0:0] cmp10301_i_fu_279_p2;
reg   [0:0] cmp10301_i_reg_393;
wire    ap_CS_fsm_state4;
wire   [0:0] xor_ln3150_fu_284_p2;
reg   [0:0] xor_ln3150_reg_398;
wire   [0:0] and_ln3150_fu_308_p2;
reg   [0:0] and_ln3150_reg_409;
wire    ap_CS_fsm_state5;
wire   [0:0] select_ln3150_fu_326_p3;
reg   [0:0] select_ln3150_reg_420;
wire    ap_CS_fsm_state8;
wire    grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_start_fu_180_ap_start;
wire    grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_start_fu_180_ap_done;
wire    grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_start_fu_180_ap_idle;
wire    grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_start_fu_180_ap_ready;
wire    grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_start_fu_180_s_axis_video1_TREADY;
wire   [23:0] grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_start_fu_180_axi_data_out;
wire    grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_start_fu_180_axi_data_out_ap_vld;
wire   [0:0] grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_start_fu_180_axi_last_out;
wire    grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_start_fu_180_axi_last_out_ap_vld;
wire    grp_AXIvideo2MultiPixStream_5_Pipeline_loop_width_fu_200_ap_start;
wire    grp_AXIvideo2MultiPixStream_5_Pipeline_loop_width_fu_200_ap_done;
wire    grp_AXIvideo2MultiPixStream_5_Pipeline_loop_width_fu_200_ap_idle;
wire    grp_AXIvideo2MultiPixStream_5_Pipeline_loop_width_fu_200_ap_ready;
wire   [23:0] grp_AXIvideo2MultiPixStream_5_Pipeline_loop_width_fu_200_srcLayer1_din;
wire    grp_AXIvideo2MultiPixStream_5_Pipeline_loop_width_fu_200_srcLayer1_write;
wire    grp_AXIvideo2MultiPixStream_5_Pipeline_loop_width_fu_200_s_axis_video1_TREADY;
wire   [0:0] grp_AXIvideo2MultiPixStream_5_Pipeline_loop_width_fu_200_eol_out;
wire    grp_AXIvideo2MultiPixStream_5_Pipeline_loop_width_fu_200_eol_out_ap_vld;
wire   [23:0] grp_AXIvideo2MultiPixStream_5_Pipeline_loop_width_fu_200_axi_data_3_out;
wire    grp_AXIvideo2MultiPixStream_5_Pipeline_loop_width_fu_200_axi_data_3_out_ap_vld;
wire    grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_eol_fu_228_ap_start;
wire    grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_eol_fu_228_ap_done;
wire    grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_eol_fu_228_ap_idle;
wire    grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_eol_fu_228_ap_ready;
wire    grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_eol_fu_228_s_axis_video1_TREADY;
wire   [23:0] grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_eol_fu_228_axi_data_4_out;
wire    grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_eol_fu_228_axi_data_4_out_ap_vld;
wire   [0:0] grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_eol_fu_228_axi_last_4_out;
wire    grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_eol_fu_228_axi_last_4_out_ap_vld;
reg    grp_reg_unsigned_short_s_fu_259_ap_start;
wire    grp_reg_unsigned_short_s_fu_259_ap_done;
wire    grp_reg_unsigned_short_s_fu_259_ap_idle;
wire    grp_reg_unsigned_short_s_fu_259_ap_ready;
reg    grp_reg_unsigned_short_s_fu_259_ap_ce;
wire   [11:0] grp_reg_unsigned_short_s_fu_259_d;
reg    ap_block_state1_ignore_call18;
reg    grp_reg_unsigned_short_s_fu_265_ap_start;
wire    grp_reg_unsigned_short_s_fu_265_ap_done;
wire    grp_reg_unsigned_short_s_fu_265_ap_idle;
wire    grp_reg_unsigned_short_s_fu_265_ap_ready;
reg    grp_reg_unsigned_short_s_fu_265_ap_ce;
wire   [11:0] grp_reg_unsigned_short_s_fu_265_d;
reg    ap_block_state1_ignore_call19;
reg   [0:0] sof_4_reg_158;
wire    ap_CS_fsm_state10;
reg   [0:0] axi_last_2_reg_170;
reg    grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_start_fu_180_ap_start_reg;
wire    ap_CS_fsm_state3;
reg   [23:0] axi_data_2_fu_108;
reg    grp_AXIvideo2MultiPixStream_5_Pipeline_loop_width_fu_200_ap_start_reg;
wire   [0:0] icmp_ln3101_fu_293_p2;
wire    ap_CS_fsm_state6;
reg    grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_eol_fu_228_ap_start_reg;
wire    ap_CS_fsm_state9;
reg   [0:0] axi_last_4_loc_fu_92;
reg   [11:0] i_fu_112;
wire   [11:0] i_4_fu_298_p2;
reg    HwReg_layerHeight_1_val_c32_write_local;
reg    HwReg_layerWidth_1_val_c24_write_local;
reg    HwReg_layerEnableFlag_1_val_c17_write_local;
reg   [9:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 10'd1;
#0 grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_start_fu_180_ap_start_reg = 1'b0;
#0 grp_AXIvideo2MultiPixStream_5_Pipeline_loop_width_fu_200_ap_start_reg = 1'b0;
#0 grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_eol_fu_228_ap_start_reg = 1'b0;
#0 i_fu_112 = 12'd0;
end

main_design_v_mix_0_0_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_start grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_start_fu_180(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_start_fu_180_ap_start),
    .ap_done(grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_start_fu_180_ap_done),
    .ap_idle(grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_start_fu_180_ap_idle),
    .ap_ready(grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_start_fu_180_ap_ready),
    .s_axis_video1_TVALID(s_axis_video1_TVALID),
    .s_axis_video1_TDATA(s_axis_video1_TDATA),
    .s_axis_video1_TREADY(grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_start_fu_180_s_axis_video1_TREADY),
    .s_axis_video1_TKEEP(s_axis_video1_TKEEP),
    .s_axis_video1_TSTRB(s_axis_video1_TSTRB),
    .s_axis_video1_TUSER(s_axis_video1_TUSER),
    .s_axis_video1_TLAST(s_axis_video1_TLAST),
    .s_axis_video1_TID(s_axis_video1_TID),
    .s_axis_video1_TDEST(s_axis_video1_TDEST),
    .axi_data_out(grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_start_fu_180_axi_data_out),
    .axi_data_out_ap_vld(grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_start_fu_180_axi_data_out_ap_vld),
    .axi_last_out(grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_start_fu_180_axi_last_out),
    .axi_last_out_ap_vld(grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_start_fu_180_axi_last_out_ap_vld)
);

main_design_v_mix_0_0_AXIvideo2MultiPixStream_5_Pipeline_loop_width grp_AXIvideo2MultiPixStream_5_Pipeline_loop_width_fu_200(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_AXIvideo2MultiPixStream_5_Pipeline_loop_width_fu_200_ap_start),
    .ap_done(grp_AXIvideo2MultiPixStream_5_Pipeline_loop_width_fu_200_ap_done),
    .ap_idle(grp_AXIvideo2MultiPixStream_5_Pipeline_loop_width_fu_200_ap_idle),
    .ap_ready(grp_AXIvideo2MultiPixStream_5_Pipeline_loop_width_fu_200_ap_ready),
    .s_axis_video1_TVALID(s_axis_video1_TVALID),
    .srcLayer1_din(grp_AXIvideo2MultiPixStream_5_Pipeline_loop_width_fu_200_srcLayer1_din),
    .srcLayer1_num_data_valid(3'd0),
    .srcLayer1_fifo_cap(3'd0),
    .srcLayer1_full_n(srcLayer1_full_n),
    .srcLayer1_write(grp_AXIvideo2MultiPixStream_5_Pipeline_loop_width_fu_200_srcLayer1_write),
    .sof_4(sof_4_reg_158),
    .axi_last_2(axi_last_2_reg_170),
    .axi_data_2(axi_data_2_fu_108),
    .cols(cols_reg_370),
    .s_axis_video1_TDATA(s_axis_video1_TDATA),
    .s_axis_video1_TREADY(grp_AXIvideo2MultiPixStream_5_Pipeline_loop_width_fu_200_s_axis_video1_TREADY),
    .s_axis_video1_TKEEP(s_axis_video1_TKEEP),
    .s_axis_video1_TSTRB(s_axis_video1_TSTRB),
    .s_axis_video1_TUSER(s_axis_video1_TUSER),
    .s_axis_video1_TLAST(s_axis_video1_TLAST),
    .s_axis_video1_TID(s_axis_video1_TID),
    .s_axis_video1_TDEST(s_axis_video1_TDEST),
    .eol_out(grp_AXIvideo2MultiPixStream_5_Pipeline_loop_width_fu_200_eol_out),
    .eol_out_ap_vld(grp_AXIvideo2MultiPixStream_5_Pipeline_loop_width_fu_200_eol_out_ap_vld),
    .axi_data_3_out(grp_AXIvideo2MultiPixStream_5_Pipeline_loop_width_fu_200_axi_data_3_out),
    .axi_data_3_out_ap_vld(grp_AXIvideo2MultiPixStream_5_Pipeline_loop_width_fu_200_axi_data_3_out_ap_vld)
);

main_design_v_mix_0_0_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_eol grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_eol_fu_228(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_eol_fu_228_ap_start),
    .ap_done(grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_eol_fu_228_ap_done),
    .ap_idle(grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_eol_fu_228_ap_idle),
    .ap_ready(grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_eol_fu_228_ap_ready),
    .s_axis_video1_TVALID(s_axis_video1_TVALID),
    .axi_data_3_reload(grp_AXIvideo2MultiPixStream_5_Pipeline_loop_width_fu_200_axi_data_3_out),
    .select_ln3150(select_ln3150_reg_420),
    .eol_reload(grp_AXIvideo2MultiPixStream_5_Pipeline_loop_width_fu_200_eol_out),
    .s_axis_video1_TDATA(s_axis_video1_TDATA),
    .s_axis_video1_TREADY(grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_eol_fu_228_s_axis_video1_TREADY),
    .s_axis_video1_TKEEP(s_axis_video1_TKEEP),
    .s_axis_video1_TSTRB(s_axis_video1_TSTRB),
    .s_axis_video1_TUSER(s_axis_video1_TUSER),
    .s_axis_video1_TLAST(s_axis_video1_TLAST),
    .s_axis_video1_TID(s_axis_video1_TID),
    .s_axis_video1_TDEST(s_axis_video1_TDEST),
    .axi_data_4_out(grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_eol_fu_228_axi_data_4_out),
    .axi_data_4_out_ap_vld(grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_eol_fu_228_axi_data_4_out_ap_vld),
    .axi_last_4_out(grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_eol_fu_228_axi_last_4_out),
    .axi_last_4_out_ap_vld(grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_eol_fu_228_axi_last_4_out_ap_vld)
);

main_design_v_mix_0_0_reg_unsigned_short_s grp_reg_unsigned_short_s_fu_259(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_reg_unsigned_short_s_fu_259_ap_start),
    .ap_done(grp_reg_unsigned_short_s_fu_259_ap_done),
    .ap_idle(grp_reg_unsigned_short_s_fu_259_ap_idle),
    .ap_ready(grp_reg_unsigned_short_s_fu_259_ap_ready),
    .ap_ce(grp_reg_unsigned_short_s_fu_259_ap_ce),
    .d(grp_reg_unsigned_short_s_fu_259_d),
    .ap_return(grp_reg_unsigned_short_s_fu_259_ap_return)
);

main_design_v_mix_0_0_reg_unsigned_short_s grp_reg_unsigned_short_s_fu_265(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_reg_unsigned_short_s_fu_265_ap_start),
    .ap_done(grp_reg_unsigned_short_s_fu_265_ap_done),
    .ap_idle(grp_reg_unsigned_short_s_fu_265_ap_idle),
    .ap_ready(grp_reg_unsigned_short_s_fu_265_ap_ready),
    .ap_ce(grp_reg_unsigned_short_s_fu_265_ap_ce),
    .d(grp_reg_unsigned_short_s_fu_265_d),
    .ap_return(grp_reg_unsigned_short_s_fu_265_ap_return)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state5) & ((1'd0 == HwReg_layerEnableFlag_1_val_read_read_fu_116_p2) | (icmp_ln3101_fu_293_p2 == 1'd1)))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_eol_fu_228_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state8)) begin
            grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_eol_fu_228_ap_start_reg <= 1'b1;
        end else if ((grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_eol_fu_228_ap_ready == 1'b1)) begin
            grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_eol_fu_228_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_start_fu_180_ap_start_reg <= 1'b0;
    end else begin
        if (((1'd1 == HwReg_layerEnableFlag_1_val_read_read_fu_116_p2) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_start_fu_180_ap_start_reg <= 1'b1;
        end else if ((grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_start_fu_180_ap_ready == 1'b1)) begin
            grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_start_fu_180_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_AXIvideo2MultiPixStream_5_Pipeline_loop_width_fu_200_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln3101_fu_293_p2 == 1'd0) & (1'd1 == HwReg_layerEnableFlag_1_val_read_read_fu_116_p2) & (1'b1 == ap_CS_fsm_state5))) begin
            grp_AXIvideo2MultiPixStream_5_Pipeline_loop_width_fu_200_ap_start_reg <= 1'b1;
        end else if ((grp_AXIvideo2MultiPixStream_5_Pipeline_loop_width_fu_200_ap_ready == 1'b1)) begin
            grp_AXIvideo2MultiPixStream_5_Pipeline_loop_width_fu_200_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_eol_fu_228_axi_data_4_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        axi_data_2_fu_108 <= grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_eol_fu_228_axi_data_4_out;
    end else if (((1'b1 == ap_CS_fsm_state3) & (grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_start_fu_180_axi_data_out_ap_vld == 1'b1))) begin
        axi_data_2_fu_108 <= grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_start_fu_180_axi_data_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        axi_last_2_reg_170 <= axi_last_4_loc_fu_92;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        axi_last_2_reg_170 <= grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_start_fu_180_axi_last_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'd1 == HwReg_layerEnableFlag_1_val_read_read_fu_116_p2)) begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            i_fu_112 <= 12'd0;
        end else if (((icmp_ln3101_fu_293_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
            i_fu_112 <= i_4_fu_298_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        sof_4_reg_158 <= and_ln3150_reg_409;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        sof_4_reg_158 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        and_ln3150_reg_409 <= and_ln3150_fu_308_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_eol_fu_228_axi_last_4_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        axi_last_4_loc_fu_92 <= grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_eol_fu_228_axi_last_4_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        cmp10301_i_reg_393 <= cmp10301_i_fu_279_p2;
        xor_ln3150_reg_398 <= xor_ln3150_fu_284_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        cols_reg_370 <= grp_reg_unsigned_short_s_fu_265_ap_return;
        rows_reg_365 <= grp_reg_unsigned_short_s_fu_259_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        select_ln3150_reg_420 <= select_ln3150_fu_326_p3;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_layerEnableFlag_1_val_c17_blk_n = HwReg_layerEnableFlag_1_val_c17_full_n;
    end else begin
        HwReg_layerEnableFlag_1_val_c17_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_layerEnableFlag_1_val_c17_write_local = 1'b1;
    end else begin
        HwReg_layerEnableFlag_1_val_c17_write_local = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_layerHeight_1_val_c32_blk_n = HwReg_layerHeight_1_val_c32_full_n;
    end else begin
        HwReg_layerHeight_1_val_c32_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_layerHeight_1_val_c32_write_local = 1'b1;
    end else begin
        HwReg_layerHeight_1_val_c32_write_local = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_layerWidth_1_val_c24_blk_n = HwReg_layerWidth_1_val_c24_full_n;
    end else begin
        HwReg_layerWidth_1_val_c24_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_layerWidth_1_val_c24_write_local = 1'b1;
    end else begin
        HwReg_layerWidth_1_val_c24_write_local = 1'b0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_start_fu_180_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_AXIvideo2MultiPixStream_5_Pipeline_loop_width_fu_200_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_eol_fu_228_ap_done == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & ((1'd0 == HwReg_layerEnableFlag_1_val_read_read_fu_116_p2) | (icmp_ln3101_fu_293_p2 == 1'd1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((1'b0 == ap_block_state1_ignore_call18) & (1'b1 == ap_CS_fsm_state1)))) begin
        grp_reg_unsigned_short_s_fu_259_ap_ce = 1'b1;
    end else begin
        grp_reg_unsigned_short_s_fu_259_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b0 == ap_block_state1_ignore_call18) & (1'b1 == ap_CS_fsm_state1))) begin
        grp_reg_unsigned_short_s_fu_259_ap_start = 1'b1;
    end else begin
        grp_reg_unsigned_short_s_fu_259_ap_start = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((1'b0 == ap_block_state1_ignore_call19) & (1'b1 == ap_CS_fsm_state1)))) begin
        grp_reg_unsigned_short_s_fu_265_ap_ce = 1'b1;
    end else begin
        grp_reg_unsigned_short_s_fu_265_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b0 == ap_block_state1_ignore_call19) & (1'b1 == ap_CS_fsm_state1))) begin
        grp_reg_unsigned_short_s_fu_265_ap_start = 1'b1;
    end else begin
        grp_reg_unsigned_short_s_fu_265_ap_start = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & ((1'd0 == HwReg_layerEnableFlag_1_val_read_read_fu_116_p2) | (icmp_ln3101_fu_293_p2 == 1'd1)))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        s_axis_video1_TREADY = grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_eol_fu_228_s_axis_video1_TREADY;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        s_axis_video1_TREADY = grp_AXIvideo2MultiPixStream_5_Pipeline_loop_width_fu_200_s_axis_video1_TREADY;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        s_axis_video1_TREADY = grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_start_fu_180_s_axis_video1_TREADY;
    end else begin
        s_axis_video1_TREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        srcLayer1_write = grp_AXIvideo2MultiPixStream_5_Pipeline_loop_width_fu_200_srcLayer1_write;
    end else begin
        srcLayer1_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'd0 == HwReg_layerEnableFlag_1_val_read_read_fu_116_p2) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_start_fu_180_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & ((1'd0 == HwReg_layerEnableFlag_1_val_read_read_fu_116_p2) | (icmp_ln3101_fu_293_p2 == 1'd1)))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (grp_AXIvideo2MultiPixStream_5_Pipeline_loop_width_fu_200_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((1'b1 == ap_CS_fsm_state9) & (grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_eol_fu_228_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign HwReg_layerEnableFlag_1_val_c17_din = HwReg_layerEnableFlag_1_val;

assign HwReg_layerEnableFlag_1_val_c17_write = HwReg_layerEnableFlag_1_val_c17_write_local;

assign HwReg_layerEnableFlag_1_val_read_read_fu_116_p2 = HwReg_layerEnableFlag_1_val;

assign HwReg_layerHeight_1_val_c32_din = HwReg_layerHeight_1_val;

assign HwReg_layerHeight_1_val_c32_write = HwReg_layerHeight_1_val_c32_write_local;

assign HwReg_layerWidth_1_val_c24_din = HwReg_layerWidth_1_val;

assign HwReg_layerWidth_1_val_c24_write = HwReg_layerWidth_1_val_c24_write_local;

assign and_ln3150_fu_308_p2 = (xor_ln3150_reg_398 & sof_4_reg_158);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = ((1'b0 == HwReg_layerHeight_1_val_c32_full_n) | (1'b0 == HwReg_layerWidth_1_val_c24_full_n) | (1'b0 == HwReg_layerEnableFlag_1_val_c17_full_n) | (ap_done_reg == 1'b1) | (real_start == 1'b0));
end

always @ (*) begin
    ap_block_state1_ignore_call18 = ((1'b0 == HwReg_layerHeight_1_val_c32_full_n) | (1'b0 == HwReg_layerWidth_1_val_c24_full_n) | (1'b0 == HwReg_layerEnableFlag_1_val_c17_full_n) | (ap_done_reg == 1'b1) | (real_start == 1'b0));
end

always @ (*) begin
    ap_block_state1_ignore_call19 = ((1'b0 == HwReg_layerHeight_1_val_c32_full_n) | (1'b0 == HwReg_layerWidth_1_val_c24_full_n) | (1'b0 == HwReg_layerEnableFlag_1_val_c17_full_n) | (ap_done_reg == 1'b1) | (real_start == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign cmp10301_i_fu_279_p2 = ((cols_reg_370 != 12'd0) ? 1'b1 : 1'b0);

assign grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_eol_fu_228_ap_start = grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_eol_fu_228_ap_start_reg;

assign grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_start_fu_180_ap_start = grp_AXIvideo2MultiPixStream_5_Pipeline_loop_wait_for_start_fu_180_ap_start_reg;

assign grp_AXIvideo2MultiPixStream_5_Pipeline_loop_width_fu_200_ap_start = grp_AXIvideo2MultiPixStream_5_Pipeline_loop_width_fu_200_ap_start_reg;

assign grp_reg_unsigned_short_s_fu_259_d = HwReg_layerHeight_1_val[11:0];

assign grp_reg_unsigned_short_s_fu_265_d = HwReg_layerWidth_1_val[11:0];

assign i_4_fu_298_p2 = (i_fu_112 + 12'd1);

assign icmp_ln3101_fu_293_p2 = ((i_fu_112 == rows_reg_365) ? 1'b1 : 1'b0);

assign select_ln3150_fu_326_p3 = ((cmp10301_i_reg_393[0:0] == 1'b1) ? grp_AXIvideo2MultiPixStream_5_Pipeline_loop_width_fu_200_eol_out : axi_last_2_reg_170);

assign srcLayer1_din = grp_AXIvideo2MultiPixStream_5_Pipeline_loop_width_fu_200_srcLayer1_din;

assign start_out = real_start;

assign xor_ln3150_fu_284_p2 = (cmp10301_i_fu_279_p2 ^ 1'd1);

endmodule //main_design_v_mix_0_0_AXIvideo2MultiPixStream_5
