-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity main_design_v_mix_0_0_AXIvideo2MultiPixStream_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    s_axis_video_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
    s_axis_video_TVALID : IN STD_LOGIC;
    s_axis_video_TREADY : OUT STD_LOGIC;
    s_axis_video_TKEEP : IN STD_LOGIC_VECTOR (2 downto 0);
    s_axis_video_TSTRB : IN STD_LOGIC_VECTOR (2 downto 0);
    s_axis_video_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axis_video_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axis_video_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axis_video_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    srcLayer0_din : OUT STD_LOGIC_VECTOR (23 downto 0);
    srcLayer0_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    srcLayer0_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    srcLayer0_full_n : IN STD_LOGIC;
    srcLayer0_write : OUT STD_LOGIC;
    Height : IN STD_LOGIC_VECTOR (11 downto 0);
    WidthIn : IN STD_LOGIC_VECTOR (11 downto 0);
    layerEnableFlag : IN STD_LOGIC_VECTOR (0 downto 0);
    HwReg_layerEnableFlag_0_val_c14_din : OUT STD_LOGIC_VECTOR (0 downto 0);
    HwReg_layerEnableFlag_0_val_c14_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    HwReg_layerEnableFlag_0_val_c14_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    HwReg_layerEnableFlag_0_val_c14_full_n : IN STD_LOGIC;
    HwReg_layerEnableFlag_0_val_c14_write : OUT STD_LOGIC );
end;


architecture behav of main_design_v_mix_0_0_AXIvideo2MultiPixStream_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (9 downto 0) := "0000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (9 downto 0) := "0000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (9 downto 0) := "0000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (9 downto 0) := "0000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (9 downto 0) := "0000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (9 downto 0) := "0001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (9 downto 0) := "0010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (9 downto 0) := "0100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (9 downto 0) := "1000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal HwReg_layerEnableFlag_0_val_c14_blk_n : STD_LOGIC;
    signal layerEnableFlag_read_read_fu_114_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal grp_reg_unsigned_short_1_fu_233_ap_return : STD_LOGIC_VECTOR (11 downto 0);
    signal rows_reg_339 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_reg_unsigned_short_1_fu_239_ap_return : STD_LOGIC_VECTOR (11 downto 0);
    signal cols_reg_344 : STD_LOGIC_VECTOR (11 downto 0);
    signal cmp10301_fu_253_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp10301_reg_367 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal xor_ln3150_fu_258_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln3150_reg_372 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln3150_fu_282_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln3150_reg_383 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal select_ln3150_fu_300_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln3150_reg_394 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_162_ap_start : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_162_ap_done : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_162_ap_idle : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_162_ap_ready : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_162_s_axis_video_TREADY : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_162_axi_data_out : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_162_axi_data_out_ap_vld : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_162_axi_last_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_162_axi_last_out_ap_vld : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_182_ap_start : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_182_ap_done : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_182_ap_idle : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_182_ap_ready : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_182_srcLayer0_din : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_182_srcLayer0_write : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_182_s_axis_video_TREADY : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_182_eol_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_182_eol_out_ap_vld : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_182_axi_data_11_out : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_182_axi_data_11_out_ap_vld : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_210_ap_start : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_210_ap_done : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_210_ap_idle : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_210_ap_ready : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_210_s_axis_video_TREADY : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_210_axi_data_4_out : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_210_axi_data_4_out_ap_vld : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_210_axi_last_4_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_210_axi_last_4_out_ap_vld : STD_LOGIC;
    signal grp_reg_unsigned_short_1_fu_233_ap_start : STD_LOGIC;
    signal grp_reg_unsigned_short_1_fu_233_ap_done : STD_LOGIC;
    signal grp_reg_unsigned_short_1_fu_233_ap_idle : STD_LOGIC;
    signal grp_reg_unsigned_short_1_fu_233_ap_ready : STD_LOGIC;
    signal grp_reg_unsigned_short_1_fu_233_ap_ce : STD_LOGIC;
    signal ap_block_state1_ignore_call14 : BOOLEAN;
    signal grp_reg_unsigned_short_1_fu_239_ap_start : STD_LOGIC;
    signal grp_reg_unsigned_short_1_fu_239_ap_done : STD_LOGIC;
    signal grp_reg_unsigned_short_1_fu_239_ap_idle : STD_LOGIC;
    signal grp_reg_unsigned_short_1_fu_239_ap_ready : STD_LOGIC;
    signal grp_reg_unsigned_short_1_fu_239_ap_ce : STD_LOGIC;
    signal ap_block_state1_ignore_call15 : BOOLEAN;
    signal sof_reg_140 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal axi_last_12_reg_152 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_162_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal axi_data_fu_106 : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_182_ap_start_reg : STD_LOGIC := '0';
    signal icmp_ln3101_fu_267_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_210_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal axi_last_4_loc_fu_90 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_fu_110 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    signal i_6_fu_272_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal HwReg_layerEnableFlag_0_val_c14_write_local : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component main_design_v_mix_0_0_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        s_axis_video_TVALID : IN STD_LOGIC;
        s_axis_video_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
        s_axis_video_TREADY : OUT STD_LOGIC;
        s_axis_video_TKEEP : IN STD_LOGIC_VECTOR (2 downto 0);
        s_axis_video_TSTRB : IN STD_LOGIC_VECTOR (2 downto 0);
        s_axis_video_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video_TID : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
        axi_data_out : OUT STD_LOGIC_VECTOR (23 downto 0);
        axi_data_out_ap_vld : OUT STD_LOGIC;
        axi_last_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        axi_last_out_ap_vld : OUT STD_LOGIC );
    end component;


    component main_design_v_mix_0_0_AXIvideo2MultiPixStream_1_Pipeline_loop_width IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        s_axis_video_TVALID : IN STD_LOGIC;
        srcLayer0_din : OUT STD_LOGIC_VECTOR (23 downto 0);
        srcLayer0_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        srcLayer0_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        srcLayer0_full_n : IN STD_LOGIC;
        srcLayer0_write : OUT STD_LOGIC;
        sof_7 : IN STD_LOGIC_VECTOR (0 downto 0);
        axi_last_12 : IN STD_LOGIC_VECTOR (0 downto 0);
        axi_data_10 : IN STD_LOGIC_VECTOR (23 downto 0);
        cols : IN STD_LOGIC_VECTOR (11 downto 0);
        s_axis_video_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
        s_axis_video_TREADY : OUT STD_LOGIC;
        s_axis_video_TKEEP : IN STD_LOGIC_VECTOR (2 downto 0);
        s_axis_video_TSTRB : IN STD_LOGIC_VECTOR (2 downto 0);
        s_axis_video_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video_TID : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
        eol_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        eol_out_ap_vld : OUT STD_LOGIC;
        axi_data_11_out : OUT STD_LOGIC_VECTOR (23 downto 0);
        axi_data_11_out_ap_vld : OUT STD_LOGIC );
    end component;


    component main_design_v_mix_0_0_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        s_axis_video_TVALID : IN STD_LOGIC;
        axi_data_11_reload : IN STD_LOGIC_VECTOR (23 downto 0);
        select_ln3150 : IN STD_LOGIC_VECTOR (0 downto 0);
        eol_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
        s_axis_video_TREADY : OUT STD_LOGIC;
        s_axis_video_TKEEP : IN STD_LOGIC_VECTOR (2 downto 0);
        s_axis_video_TSTRB : IN STD_LOGIC_VECTOR (2 downto 0);
        s_axis_video_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video_TID : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
        axi_data_4_out : OUT STD_LOGIC_VECTOR (23 downto 0);
        axi_data_4_out_ap_vld : OUT STD_LOGIC;
        axi_last_4_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        axi_last_4_out_ap_vld : OUT STD_LOGIC );
    end component;


    component main_design_v_mix_0_0_reg_unsigned_short_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_ce : IN STD_LOGIC;
        d : IN STD_LOGIC_VECTOR (11 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (11 downto 0) );
    end component;



begin
    grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_162 : component main_design_v_mix_0_0_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_162_ap_start,
        ap_done => grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_162_ap_done,
        ap_idle => grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_162_ap_idle,
        ap_ready => grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_162_ap_ready,
        s_axis_video_TVALID => s_axis_video_TVALID,
        s_axis_video_TDATA => s_axis_video_TDATA,
        s_axis_video_TREADY => grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_162_s_axis_video_TREADY,
        s_axis_video_TKEEP => s_axis_video_TKEEP,
        s_axis_video_TSTRB => s_axis_video_TSTRB,
        s_axis_video_TUSER => s_axis_video_TUSER,
        s_axis_video_TLAST => s_axis_video_TLAST,
        s_axis_video_TID => s_axis_video_TID,
        s_axis_video_TDEST => s_axis_video_TDEST,
        axi_data_out => grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_162_axi_data_out,
        axi_data_out_ap_vld => grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_162_axi_data_out_ap_vld,
        axi_last_out => grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_162_axi_last_out,
        axi_last_out_ap_vld => grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_162_axi_last_out_ap_vld);

    grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_182 : component main_design_v_mix_0_0_AXIvideo2MultiPixStream_1_Pipeline_loop_width
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_182_ap_start,
        ap_done => grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_182_ap_done,
        ap_idle => grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_182_ap_idle,
        ap_ready => grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_182_ap_ready,
        s_axis_video_TVALID => s_axis_video_TVALID,
        srcLayer0_din => grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_182_srcLayer0_din,
        srcLayer0_num_data_valid => ap_const_lv3_0,
        srcLayer0_fifo_cap => ap_const_lv3_0,
        srcLayer0_full_n => srcLayer0_full_n,
        srcLayer0_write => grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_182_srcLayer0_write,
        sof_7 => sof_reg_140,
        axi_last_12 => axi_last_12_reg_152,
        axi_data_10 => axi_data_fu_106,
        cols => cols_reg_344,
        s_axis_video_TDATA => s_axis_video_TDATA,
        s_axis_video_TREADY => grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_182_s_axis_video_TREADY,
        s_axis_video_TKEEP => s_axis_video_TKEEP,
        s_axis_video_TSTRB => s_axis_video_TSTRB,
        s_axis_video_TUSER => s_axis_video_TUSER,
        s_axis_video_TLAST => s_axis_video_TLAST,
        s_axis_video_TID => s_axis_video_TID,
        s_axis_video_TDEST => s_axis_video_TDEST,
        eol_out => grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_182_eol_out,
        eol_out_ap_vld => grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_182_eol_out_ap_vld,
        axi_data_11_out => grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_182_axi_data_11_out,
        axi_data_11_out_ap_vld => grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_182_axi_data_11_out_ap_vld);

    grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_210 : component main_design_v_mix_0_0_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_210_ap_start,
        ap_done => grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_210_ap_done,
        ap_idle => grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_210_ap_idle,
        ap_ready => grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_210_ap_ready,
        s_axis_video_TVALID => s_axis_video_TVALID,
        axi_data_11_reload => grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_182_axi_data_11_out,
        select_ln3150 => select_ln3150_reg_394,
        eol_reload => grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_182_eol_out,
        s_axis_video_TDATA => s_axis_video_TDATA,
        s_axis_video_TREADY => grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_210_s_axis_video_TREADY,
        s_axis_video_TKEEP => s_axis_video_TKEEP,
        s_axis_video_TSTRB => s_axis_video_TSTRB,
        s_axis_video_TUSER => s_axis_video_TUSER,
        s_axis_video_TLAST => s_axis_video_TLAST,
        s_axis_video_TID => s_axis_video_TID,
        s_axis_video_TDEST => s_axis_video_TDEST,
        axi_data_4_out => grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_210_axi_data_4_out,
        axi_data_4_out_ap_vld => grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_210_axi_data_4_out_ap_vld,
        axi_last_4_out => grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_210_axi_last_4_out,
        axi_last_4_out_ap_vld => grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_210_axi_last_4_out_ap_vld);

    grp_reg_unsigned_short_1_fu_233 : component main_design_v_mix_0_0_reg_unsigned_short_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_reg_unsigned_short_1_fu_233_ap_start,
        ap_done => grp_reg_unsigned_short_1_fu_233_ap_done,
        ap_idle => grp_reg_unsigned_short_1_fu_233_ap_idle,
        ap_ready => grp_reg_unsigned_short_1_fu_233_ap_ready,
        ap_ce => grp_reg_unsigned_short_1_fu_233_ap_ce,
        d => Height,
        ap_return => grp_reg_unsigned_short_1_fu_233_ap_return);

    grp_reg_unsigned_short_1_fu_239 : component main_design_v_mix_0_0_reg_unsigned_short_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_reg_unsigned_short_1_fu_239_ap_start,
        ap_done => grp_reg_unsigned_short_1_fu_239_ap_done,
        ap_idle => grp_reg_unsigned_short_1_fu_239_ap_idle,
        ap_ready => grp_reg_unsigned_short_1_fu_239_ap_ready,
        ap_ce => grp_reg_unsigned_short_1_fu_239_ap_ce,
        d => WidthIn,
        ap_return => grp_reg_unsigned_short_1_fu_239_ap_return);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and ((layerEnableFlag_read_read_fu_114_p2 = ap_const_lv1_0) or (icmp_ln3101_fu_267_p2 = ap_const_lv1_1)))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_210_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_210_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                    grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_210_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_210_ap_ready = ap_const_logic_1)) then 
                    grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_210_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_162_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_162_ap_start_reg <= ap_const_logic_0;
            else
                if (((layerEnableFlag_read_read_fu_114_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_162_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_162_ap_ready = ap_const_logic_1)) then 
                    grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_162_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_182_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_182_ap_start_reg <= ap_const_logic_0;
            else
                if (((layerEnableFlag_read_read_fu_114_p2 = ap_const_lv1_1) and (icmp_ln3101_fu_267_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                    grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_182_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_182_ap_ready = ap_const_logic_1)) then 
                    grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_182_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    axi_data_fu_106_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state9) and (grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_210_axi_data_4_out_ap_vld = ap_const_logic_1))) then 
                axi_data_fu_106 <= grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_210_axi_data_4_out;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_162_axi_data_out_ap_vld = ap_const_logic_1))) then 
                axi_data_fu_106 <= grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_162_axi_data_out;
            end if; 
        end if;
    end process;

    axi_last_12_reg_152_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
                axi_last_12_reg_152 <= axi_last_4_loc_fu_90;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                axi_last_12_reg_152 <= grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_162_axi_last_out;
            end if; 
        end if;
    end process;

    i_fu_110_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((layerEnableFlag_read_read_fu_114_p2 = ap_const_lv1_1)) then
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    i_fu_110 <= ap_const_lv12_0;
                elsif (((icmp_ln3101_fu_267_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                    i_fu_110 <= i_6_fu_272_p2;
                end if;
            end if; 
        end if;
    end process;

    sof_reg_140_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
                sof_reg_140 <= and_ln3150_reg_383;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                sof_reg_140 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                and_ln3150_reg_383 <= and_ln3150_fu_282_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state9) and (grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_210_axi_last_4_out_ap_vld = ap_const_logic_1))) then
                axi_last_4_loc_fu_90 <= grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_210_axi_last_4_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                cmp10301_reg_367 <= cmp10301_fu_253_p2;
                xor_ln3150_reg_372 <= xor_ln3150_fu_258_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                cols_reg_344 <= grp_reg_unsigned_short_1_fu_239_ap_return;
                rows_reg_339 <= grp_reg_unsigned_short_1_fu_233_ap_return;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then
                select_ln3150_reg_394 <= select_ln3150_fu_300_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, layerEnableFlag_read_read_fu_114_p2, ap_block_state1, ap_CS_fsm_state2, ap_CS_fsm_state5, grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_162_ap_done, grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_182_ap_done, grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_210_ap_done, ap_CS_fsm_state3, icmp_ln3101_fu_267_p2, ap_CS_fsm_state6, ap_CS_fsm_state9)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((layerEnableFlag_read_read_fu_114_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_162_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and ((layerEnableFlag_read_read_fu_114_p2 = ap_const_lv1_0) or (icmp_ln3101_fu_267_p2 = ap_const_lv1_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state6 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_182_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state9) and (grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_210_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state10;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXX";
        end case;
    end process;

    HwReg_layerEnableFlag_0_val_c14_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, HwReg_layerEnableFlag_0_val_c14_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            HwReg_layerEnableFlag_0_val_c14_blk_n <= HwReg_layerEnableFlag_0_val_c14_full_n;
        else 
            HwReg_layerEnableFlag_0_val_c14_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    HwReg_layerEnableFlag_0_val_c14_din <= layerEnableFlag;
    HwReg_layerEnableFlag_0_val_c14_write <= HwReg_layerEnableFlag_0_val_c14_write_local;

    HwReg_layerEnableFlag_0_val_c14_write_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            HwReg_layerEnableFlag_0_val_c14_write_local <= ap_const_logic_1;
        else 
            HwReg_layerEnableFlag_0_val_c14_write_local <= ap_const_logic_0;
        end if; 
    end process;

    and_ln3150_fu_282_p2 <= (xor_ln3150_reg_372 and sof_reg_140);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_162_ap_done)
    begin
        if ((grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_162_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_182_ap_done)
    begin
        if ((grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_182_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;

    ap_ST_fsm_state9_blk_assign_proc : process(grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_210_ap_done)
    begin
        if ((grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_210_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state9_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state9_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg, HwReg_layerEnableFlag_0_val_c14_full_n)
    begin
                ap_block_state1 <= ((ap_const_logic_0 = HwReg_layerEnableFlag_0_val_c14_full_n) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_block_state1_ignore_call14_assign_proc : process(real_start, ap_done_reg, HwReg_layerEnableFlag_0_val_c14_full_n)
    begin
                ap_block_state1_ignore_call14 <= ((ap_const_logic_0 = HwReg_layerEnableFlag_0_val_c14_full_n) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_block_state1_ignore_call15_assign_proc : process(real_start, ap_done_reg, HwReg_layerEnableFlag_0_val_c14_full_n)
    begin
                ap_block_state1_ignore_call15 <= ((ap_const_logic_0 = HwReg_layerEnableFlag_0_val_c14_full_n) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, layerEnableFlag_read_read_fu_114_p2, ap_CS_fsm_state5, icmp_ln3101_fu_267_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and ((layerEnableFlag_read_read_fu_114_p2 = ap_const_lv1_0) or (icmp_ln3101_fu_267_p2 = ap_const_lv1_1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    cmp10301_fu_253_p2 <= "0" when (cols_reg_344 = ap_const_lv12_0) else "1";
    grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_210_ap_start <= grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_210_ap_start_reg;
    grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_162_ap_start <= grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_162_ap_start_reg;
    grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_182_ap_start <= grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_182_ap_start_reg;

    grp_reg_unsigned_short_1_fu_233_ap_ce_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2, ap_block_state1_ignore_call14)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_boolean_0 = ap_block_state1_ignore_call14) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            grp_reg_unsigned_short_1_fu_233_ap_ce <= ap_const_logic_1;
        else 
            grp_reg_unsigned_short_1_fu_233_ap_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_reg_unsigned_short_1_fu_233_ap_start_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, ap_block_state1_ignore_call14)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_boolean_0 = ap_block_state1_ignore_call14) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            grp_reg_unsigned_short_1_fu_233_ap_start <= ap_const_logic_1;
        else 
            grp_reg_unsigned_short_1_fu_233_ap_start <= ap_const_logic_0;
        end if; 
    end process;


    grp_reg_unsigned_short_1_fu_239_ap_ce_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2, ap_block_state1_ignore_call15)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_boolean_0 = ap_block_state1_ignore_call15) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            grp_reg_unsigned_short_1_fu_239_ap_ce <= ap_const_logic_1;
        else 
            grp_reg_unsigned_short_1_fu_239_ap_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_reg_unsigned_short_1_fu_239_ap_start_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, ap_block_state1_ignore_call15)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_boolean_0 = ap_block_state1_ignore_call15) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            grp_reg_unsigned_short_1_fu_239_ap_start <= ap_const_logic_1;
        else 
            grp_reg_unsigned_short_1_fu_239_ap_start <= ap_const_logic_0;
        end if; 
    end process;

    i_6_fu_272_p2 <= std_logic_vector(unsigned(i_fu_110) + unsigned(ap_const_lv12_1));
    icmp_ln3101_fu_267_p2 <= "1" when (i_fu_110 = rows_reg_339) else "0";

    internal_ap_ready_assign_proc : process(layerEnableFlag_read_read_fu_114_p2, ap_CS_fsm_state5, icmp_ln3101_fu_267_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and ((layerEnableFlag_read_read_fu_114_p2 = ap_const_lv1_0) or (icmp_ln3101_fu_267_p2 = ap_const_lv1_1)))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    layerEnableFlag_read_read_fu_114_p2 <= layerEnableFlag;

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;


    s_axis_video_TREADY_assign_proc : process(grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_162_s_axis_video_TREADY, grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_182_s_axis_video_TREADY, grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_210_s_axis_video_TREADY, ap_CS_fsm_state3, ap_CS_fsm_state6, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            s_axis_video_TREADY <= grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_210_s_axis_video_TREADY;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            s_axis_video_TREADY <= grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_182_s_axis_video_TREADY;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            s_axis_video_TREADY <= grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_162_s_axis_video_TREADY;
        else 
            s_axis_video_TREADY <= ap_const_logic_0;
        end if; 
    end process;

    select_ln3150_fu_300_p3 <= 
        grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_182_eol_out when (cmp10301_reg_367(0) = '1') else 
        axi_last_12_reg_152;
    srcLayer0_din <= grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_182_srcLayer0_din;

    srcLayer0_write_assign_proc : process(grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_182_srcLayer0_write, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            srcLayer0_write <= grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_182_srcLayer0_write;
        else 
            srcLayer0_write <= ap_const_logic_0;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    xor_ln3150_fu_258_p2 <= (cmp10301_fu_253_p2 xor ap_const_lv1_1);
end behav;
