// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module main_design_v_mix_0_0_AXIvideo2MultiPixStream_5_Pipeline_loop_width (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        s_axis_video1_TVALID,
        srcLayer1_din,
        srcLayer1_num_data_valid,
        srcLayer1_fifo_cap,
        srcLayer1_full_n,
        srcLayer1_write,
        sof_4,
        axi_last_2,
        axi_data_2,
        cols,
        s_axis_video1_TDATA,
        s_axis_video1_TREADY,
        s_axis_video1_TKEEP,
        s_axis_video1_TSTRB,
        s_axis_video1_TUSER,
        s_axis_video1_TLAST,
        s_axis_video1_TID,
        s_axis_video1_TDEST,
        eol_out,
        eol_out_ap_vld,
        axi_data_3_out,
        axi_data_3_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   s_axis_video1_TVALID;
output  [23:0] srcLayer1_din;
input  [2:0] srcLayer1_num_data_valid;
input  [2:0] srcLayer1_fifo_cap;
input   srcLayer1_full_n;
output   srcLayer1_write;
input  [0:0] sof_4;
input  [0:0] axi_last_2;
input  [23:0] axi_data_2;
input  [11:0] cols;
input  [23:0] s_axis_video1_TDATA;
output   s_axis_video1_TREADY;
input  [2:0] s_axis_video1_TKEEP;
input  [2:0] s_axis_video1_TSTRB;
input  [0:0] s_axis_video1_TUSER;
input  [0:0] s_axis_video1_TLAST;
input  [0:0] s_axis_video1_TID;
input  [0:0] s_axis_video1_TDEST;
output  [0:0] eol_out;
output   eol_out_ap_vld;
output  [23:0] axi_data_3_out;
output   axi_data_3_out_ap_vld;

reg ap_idle;
reg s_axis_video1_TREADY;
reg eol_out_ap_vld;
reg axi_data_3_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire   [0:0] icmp_ln3105_fu_203_p2;
wire   [0:0] or_ln3109_fu_215_p2;
reg    ap_predicate_op36_read_state1;
reg    ap_block_state1_pp0_stage0_iter0;
reg   [0:0] icmp_ln3105_reg_299;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    srcLayer1_blk_n;
wire    ap_block_pp0_stage0;
reg    s_axis_video1_TDATA_blk_n;
reg   [0:0] eol_reg_163;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] ap_phi_mux_eol_phi_fu_166_p4;
wire    ap_loop_init;
reg   [0:0] ap_phi_mux_sof_phi_fu_177_p4;
reg   [11:0] j_fu_88;
wire   [11:0] j_6_fu_209_p2;
reg   [11:0] ap_sig_allocacmp_j_5;
reg   [23:0] axi_data_3_fu_92;
reg   [0:0] axi_last_3_fu_96;
wire   [23:0] or_ln3147_3_i_fu_264_p3;
reg    ap_block_pp0_stage0_01001;
reg    srcLayer1_write_local;
wire   [15:0] trunc_ln3147_fu_260_p1;
wire   [7:0] tmp_6_i1_fu_250_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_248;
reg    ap_condition_251;
reg    ap_condition_256;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 j_fu_88 = 12'd0;
#0 axi_data_3_fu_92 = 24'd0;
#0 axi_last_3_fu_96 = 1'd0;
#0 ap_done_reg = 1'b0;
end

main_design_v_mix_0_0_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((1'b1 == ap_condition_251)) begin
            axi_data_3_fu_92 <= s_axis_video1_TDATA;
        end else if ((ap_loop_init == 1'b1)) begin
            axi_data_3_fu_92 <= axi_data_2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((1'b1 == ap_condition_251)) begin
            axi_last_3_fu_96 <= s_axis_video1_TLAST;
        end else if ((ap_loop_init == 1'b1)) begin
            axi_last_3_fu_96 <= axi_last_2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_256)) begin
            eol_reg_163 <= axi_last_3_fu_96;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init == 1'b1))) begin
            eol_reg_163 <= 1'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln3105_fu_203_p2 == 1'd0) & (ap_start_int == 1'b1))) begin
            j_fu_88 <= j_6_fu_209_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_88 <= 12'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln3105_reg_299 <= icmp_ln3105_fu_203_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln3105_fu_203_p2 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_248)) begin
            ap_phi_mux_eol_phi_fu_166_p4 = axi_last_3_fu_96;
        end else if ((ap_loop_init == 1'b1)) begin
            ap_phi_mux_eol_phi_fu_166_p4 = 1'd0;
        end else begin
            ap_phi_mux_eol_phi_fu_166_p4 = eol_reg_163;
        end
    end else begin
        ap_phi_mux_eol_phi_fu_166_p4 = eol_reg_163;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_248)) begin
            ap_phi_mux_sof_phi_fu_177_p4 = 1'd0;
        end else if ((ap_loop_init == 1'b1)) begin
            ap_phi_mux_sof_phi_fu_177_p4 = sof_4;
        end else begin
            ap_phi_mux_sof_phi_fu_177_p4 = 1'd0;
        end
    end else begin
        ap_phi_mux_sof_phi_fu_177_p4 = 1'd0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_j_5 = 12'd0;
    end else begin
        ap_sig_allocacmp_j_5 = j_fu_88;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln3105_fu_203_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        axi_data_3_out_ap_vld = 1'b1;
    end else begin
        axi_data_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln3105_fu_203_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        eol_out_ap_vld = 1'b1;
    end else begin
        eol_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op36_read_state1 == 1'b1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_axis_video1_TDATA_blk_n = s_axis_video1_TVALID;
    end else begin
        s_axis_video1_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op36_read_state1 == 1'b1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_axis_video1_TREADY = 1'b1;
    end else begin
        s_axis_video1_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln3105_reg_299 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        srcLayer1_blk_n = srcLayer1_full_n;
    end else begin
        srcLayer1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln3105_reg_299 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        srcLayer1_write_local = 1'b1;
    end else begin
        srcLayer1_write_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_predicate_op36_read_state1 == 1'b1) & (s_axis_video1_TVALID == 1'b0));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((icmp_ln3105_reg_299 == 1'd0) & (srcLayer1_full_n == 1'b0));
end

always @ (*) begin
    ap_condition_248 = ((icmp_ln3105_reg_299 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_251 = ((or_ln3109_fu_215_p2 == 1'd0) & (icmp_ln3105_fu_203_p2 == 1'd0) & (ap_start_int == 1'b1));
end

always @ (*) begin
    ap_condition_256 = ((icmp_ln3105_reg_299 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

always @ (*) begin
    ap_predicate_op36_read_state1 = ((or_ln3109_fu_215_p2 == 1'd0) & (icmp_ln3105_fu_203_p2 == 1'd0));
end

assign ap_ready = ap_ready_sig;

assign axi_data_3_out = axi_data_3_fu_92;

assign eol_out = eol_reg_163;

assign icmp_ln3105_fu_203_p2 = ((ap_sig_allocacmp_j_5 == cols) ? 1'b1 : 1'b0);

assign j_6_fu_209_p2 = (ap_sig_allocacmp_j_5 + 12'd1);

assign or_ln3109_fu_215_p2 = (ap_phi_mux_sof_phi_fu_177_p4 | ap_phi_mux_eol_phi_fu_166_p4);

assign or_ln3147_3_i_fu_264_p3 = {{trunc_ln3147_fu_260_p1}, {tmp_6_i1_fu_250_p4}};

assign srcLayer1_din = or_ln3147_3_i_fu_264_p3;

assign srcLayer1_write = srcLayer1_write_local;

assign tmp_6_i1_fu_250_p4 = {{axi_data_3_fu_92[23:16]}};

assign trunc_ln3147_fu_260_p1 = axi_data_3_fu_92[15:0];

endmodule //main_design_v_mix_0_0_AXIvideo2MultiPixStream_5_Pipeline_loop_width
