# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param simulator.questaInstallPath C:/CaeTools/QuestaSim/win64
set_param synth.incrementalSynthesisCache C:/Projects/A_Series_7/LvdsSerialAdc/Projects/Adc_Interface/Vivado/.Xil/Vivado-2080-XBEDEFOSSEZ31/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7k325tffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Projects/A_Series_7/LvdsSerialAdc/Projects/Adc_Interface/Vivado/AdcToplevel/AdcToplevel.cache/wt [current_project]
set_property parent.project_path C:/Projects/A_Series_7/LvdsSerialAdc/Projects/Adc_Interface/Vivado/AdcToplevel/AdcToplevel.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_cache_permissions disable [current_project]
read_vhdl -library AdcClock_Lib C:/Projects/A_Series_7/LvdsSerialAdc/Projects/Adc_Interface/Libraries/AdcClock_Lib/Vhdl/AdcClock.vhd
read_vhdl -library AdcData_Lib C:/Projects/A_Series_7/LvdsSerialAdc/Projects/Adc_Interface/Libraries/AdcData_Lib/Vhdl/AdcData.vhd
read_vhdl -library Common {
  C:/Projects/A_Series_7/LvdsSerialAdc/Projects/Adc_Interface/Libraries/Common/Vhdl/Cnt_5b_Bin.vhd
  C:/Projects/A_Series_7/LvdsSerialAdc/Projects/Adc_Interface/Libraries/Common/Vhdl/Fdcr.vhd
  C:/Projects/A_Series_7/LvdsSerialAdc/Projects/Adc_Interface/Libraries/Common/Vhdl/GenPulse.vhd
  C:/Projects/A_Series_7/LvdsSerialAdc/Projects/Adc_Interface/Libraries/Common/Vhdl/Fdrse.vhd
}
read_vhdl -library AdcFrame_Lib {
  C:/Projects/A_Series_7/LvdsSerialAdc/Projects/Adc_Interface/Libraries/AdcFrame_Lib/Vhdl/DoubleNibbleDetect.vhd
  C:/Projects/A_Series_7/LvdsSerialAdc/Projects/Adc_Interface/Libraries/AdcFrame_Lib/Vhdl/AdcFrame.vhd
}
read_vhdl -library AdcMem_Lib C:/Projects/A_Series_7/LvdsSerialAdc/Projects/Adc_Interface/Libraries/AdcMem_Lib/Vhdl/AdcMem.vhd
read_vhdl -library xil_defaultlib {
  C:/Projects/A_Series_7/LvdsSerialAdc/Projects/Adc_Interface/Vhdl/AdcToplevel.vhd
  C:/Projects/A_Series_7/LvdsSerialAdc/Projects/Adc_Interface/Vhdl/AdcToplevel_Toplevel.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Projects/A_Series_7/LvdsSerialAdc/Projects/Adc_Interface/Constraints/KC705_AdcToplevel_Toplevel.xdc
set_property used_in_implementation false [get_files C:/Projects/A_Series_7/LvdsSerialAdc/Projects/Adc_Interface/Constraints/KC705_AdcToplevel_Toplevel.xdc]


synth_design -top AdcToplevel_Toplevel -part xc7k325tffg900-2 -mode out_of_context


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef AdcToplevel_Toplevel.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file AdcToplevel_Toplevel_utilization_synth.rpt -pb AdcToplevel_Toplevel_utilization_synth.pb"
