// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module main_design_v_mix_0_0_MultiPixStream2AXIvideo (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        out420_dout,
        out420_num_data_valid,
        out420_fifo_cap,
        out420_empty_n,
        out420_read,
        m_axis_video_TDATA,
        m_axis_video_TVALID,
        m_axis_video_TREADY,
        m_axis_video_TKEEP,
        m_axis_video_TSTRB,
        m_axis_video_TUSER,
        m_axis_video_TLAST,
        m_axis_video_TID,
        m_axis_video_TDEST,
        Height,
        WidthOut
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [23:0] out420_dout;
input  [2:0] out420_num_data_valid;
input  [2:0] out420_fifo_cap;
input   out420_empty_n;
output   out420_read;
output  [23:0] m_axis_video_TDATA;
output   m_axis_video_TVALID;
input   m_axis_video_TREADY;
output  [2:0] m_axis_video_TKEEP;
output  [2:0] m_axis_video_TSTRB;
output  [0:0] m_axis_video_TUSER;
output  [0:0] m_axis_video_TLAST;
output  [0:0] m_axis_video_TID;
output  [0:0] m_axis_video_TDEST;
input  [11:0] Height;
input  [11:0] WidthOut;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg out420_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [11:0] grp_reg_unsigned_short_1_fu_122_ap_return;
reg   [11:0] rows_reg_186;
wire    ap_CS_fsm_state2;
wire   [11:0] grp_reg_unsigned_short_1_fu_128_ap_return;
reg   [11:0] cols_reg_191;
wire   [12:0] sub_fu_143_p2;
reg   [12:0] sub_reg_196;
wire   [0:0] icmp_ln3231_fu_149_p2;
reg   [0:0] icmp_ln3231_reg_201;
wire   [0:0] and_ln3231_fu_169_p2;
reg   [0:0] and_ln3231_reg_209;
wire    ap_CS_fsm_state3;
wire    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_3233_3_fu_98_ap_start;
wire    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_3233_3_fu_98_ap_done;
wire    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_3233_3_fu_98_ap_idle;
wire    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_3233_3_fu_98_ap_ready;
wire    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_3233_3_fu_98_out420_read;
wire    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_3233_3_fu_98_m_axis_video_TREADY;
wire   [23:0] grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_3233_3_fu_98_m_axis_video_TDATA;
wire    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_3233_3_fu_98_m_axis_video_TVALID;
wire   [2:0] grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_3233_3_fu_98_m_axis_video_TKEEP;
wire   [2:0] grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_3233_3_fu_98_m_axis_video_TSTRB;
wire   [0:0] grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_3233_3_fu_98_m_axis_video_TUSER;
wire   [0:0] grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_3233_3_fu_98_m_axis_video_TLAST;
wire   [0:0] grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_3233_3_fu_98_m_axis_video_TID;
wire   [0:0] grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_3233_3_fu_98_m_axis_video_TDEST;
reg    grp_reg_unsigned_short_1_fu_122_ap_start;
wire    grp_reg_unsigned_short_1_fu_122_ap_done;
wire    grp_reg_unsigned_short_1_fu_122_ap_idle;
wire    grp_reg_unsigned_short_1_fu_122_ap_ready;
reg    grp_reg_unsigned_short_1_fu_122_ap_ce;
reg    ap_block_state1;
reg    ap_block_state1_ignore_call8;
reg    grp_reg_unsigned_short_1_fu_128_ap_start;
wire    grp_reg_unsigned_short_1_fu_128_ap_done;
wire    grp_reg_unsigned_short_1_fu_128_ap_idle;
wire    grp_reg_unsigned_short_1_fu_128_ap_ready;
reg    grp_reg_unsigned_short_1_fu_128_ap_ce;
reg    ap_block_state1_ignore_call9;
reg   [0:0] sof_reg_86;
wire    ap_CS_fsm_state4;
reg    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_3233_3_fu_98_ap_start_reg;
wire   [0:0] icmp_ln3231_1_fu_158_p2;
reg   [11:0] i_fu_70;
wire   [11:0] i_2_fu_163_p2;
wire   [12:0] zext_ln3183_fu_139_p1;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_3233_3_fu_98_ap_start_reg = 1'b0;
#0 i_fu_70 = 12'd0;
end

main_design_v_mix_0_0_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_3233_3 grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_3233_3_fu_98(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_3233_3_fu_98_ap_start),
    .ap_done(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_3233_3_fu_98_ap_done),
    .ap_idle(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_3233_3_fu_98_ap_idle),
    .ap_ready(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_3233_3_fu_98_ap_ready),
    .out420_dout(out420_dout),
    .out420_num_data_valid(3'd0),
    .out420_fifo_cap(3'd0),
    .out420_empty_n(out420_empty_n),
    .out420_read(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_3233_3_fu_98_out420_read),
    .m_axis_video_TREADY(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_3233_3_fu_98_m_axis_video_TREADY),
    .sof(sof_reg_86),
    .cols(cols_reg_191),
    .sub(sub_reg_196),
    .m_axis_video_TDATA(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_3233_3_fu_98_m_axis_video_TDATA),
    .m_axis_video_TVALID(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_3233_3_fu_98_m_axis_video_TVALID),
    .m_axis_video_TKEEP(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_3233_3_fu_98_m_axis_video_TKEEP),
    .m_axis_video_TSTRB(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_3233_3_fu_98_m_axis_video_TSTRB),
    .m_axis_video_TUSER(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_3233_3_fu_98_m_axis_video_TUSER),
    .m_axis_video_TLAST(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_3233_3_fu_98_m_axis_video_TLAST),
    .m_axis_video_TID(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_3233_3_fu_98_m_axis_video_TID),
    .m_axis_video_TDEST(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_3233_3_fu_98_m_axis_video_TDEST)
);

main_design_v_mix_0_0_reg_unsigned_short_1 grp_reg_unsigned_short_1_fu_122(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_reg_unsigned_short_1_fu_122_ap_start),
    .ap_done(grp_reg_unsigned_short_1_fu_122_ap_done),
    .ap_idle(grp_reg_unsigned_short_1_fu_122_ap_idle),
    .ap_ready(grp_reg_unsigned_short_1_fu_122_ap_ready),
    .ap_ce(grp_reg_unsigned_short_1_fu_122_ap_ce),
    .d(Height),
    .ap_return(grp_reg_unsigned_short_1_fu_122_ap_return)
);

main_design_v_mix_0_0_reg_unsigned_short_1 grp_reg_unsigned_short_1_fu_128(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_reg_unsigned_short_1_fu_128_ap_start),
    .ap_done(grp_reg_unsigned_short_1_fu_128_ap_done),
    .ap_idle(grp_reg_unsigned_short_1_fu_128_ap_idle),
    .ap_ready(grp_reg_unsigned_short_1_fu_128_ap_ready),
    .ap_ce(grp_reg_unsigned_short_1_fu_128_ap_ce),
    .d(WidthOut),
    .ap_return(grp_reg_unsigned_short_1_fu_128_ap_return)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln3231_1_fu_158_p2 == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_3233_3_fu_98_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln3231_1_fu_158_p2 == 1'd0))) begin
            grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_3233_3_fu_98_ap_start_reg <= 1'b1;
        end else if ((grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_3233_3_fu_98_ap_ready == 1'b1)) begin
            grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_3233_3_fu_98_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        i_fu_70 <= 12'd0;
    end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln3231_1_fu_158_p2 == 1'd0))) begin
        i_fu_70 <= i_2_fu_163_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_3233_3_fu_98_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        sof_reg_86 <= and_ln3231_reg_209;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        sof_reg_86 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        and_ln3231_reg_209 <= and_ln3231_fu_169_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        cols_reg_191 <= grp_reg_unsigned_short_1_fu_128_ap_return;
        icmp_ln3231_reg_201 <= icmp_ln3231_fu_149_p2;
        rows_reg_186 <= grp_reg_unsigned_short_1_fu_122_ap_return;
        sub_reg_196 <= sub_fu_143_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_3233_3_fu_98_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln3231_1_fu_158_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln3231_1_fu_158_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1_ignore_call8)))) begin
        grp_reg_unsigned_short_1_fu_122_ap_ce = 1'b1;
    end else begin
        grp_reg_unsigned_short_1_fu_122_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1_ignore_call8))) begin
        grp_reg_unsigned_short_1_fu_122_ap_start = 1'b1;
    end else begin
        grp_reg_unsigned_short_1_fu_122_ap_start = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1_ignore_call9)))) begin
        grp_reg_unsigned_short_1_fu_128_ap_ce = 1'b1;
    end else begin
        grp_reg_unsigned_short_1_fu_128_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1_ignore_call9))) begin
        grp_reg_unsigned_short_1_fu_128_ap_start = 1'b1;
    end else begin
        grp_reg_unsigned_short_1_fu_128_ap_start = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        out420_read = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_3233_3_fu_98_out420_read;
    end else begin
        out420_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln3231_1_fu_158_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_3233_3_fu_98_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign and_ln3231_fu_169_p2 = (sof_reg_86 & icmp_ln3231_reg_201);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state1_ignore_call8 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state1_ignore_call9 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_3233_3_fu_98_ap_start = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_3233_3_fu_98_ap_start_reg;

assign grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_3233_3_fu_98_m_axis_video_TREADY = (m_axis_video_TREADY & ap_CS_fsm_state4);

assign i_2_fu_163_p2 = (i_fu_70 + 12'd1);

assign icmp_ln3231_1_fu_158_p2 = ((i_fu_70 == rows_reg_186) ? 1'b1 : 1'b0);

assign icmp_ln3231_fu_149_p2 = ((grp_reg_unsigned_short_1_fu_128_ap_return == 12'd0) ? 1'b1 : 1'b0);

assign m_axis_video_TDATA = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_3233_3_fu_98_m_axis_video_TDATA;

assign m_axis_video_TDEST = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_3233_3_fu_98_m_axis_video_TDEST;

assign m_axis_video_TID = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_3233_3_fu_98_m_axis_video_TID;

assign m_axis_video_TKEEP = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_3233_3_fu_98_m_axis_video_TKEEP;

assign m_axis_video_TLAST = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_3233_3_fu_98_m_axis_video_TLAST;

assign m_axis_video_TSTRB = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_3233_3_fu_98_m_axis_video_TSTRB;

assign m_axis_video_TUSER = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_3233_3_fu_98_m_axis_video_TUSER;

assign m_axis_video_TVALID = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_3233_3_fu_98_m_axis_video_TVALID;

assign sub_fu_143_p2 = ($signed(zext_ln3183_fu_139_p1) + $signed(13'd8191));

assign zext_ln3183_fu_139_p1 = grp_reg_unsigned_short_1_fu_128_ap_return;

endmodule //main_design_v_mix_0_0_MultiPixStream2AXIvideo
