
# Create work library
vlib work
vlib msim
vlib msim/blk_mem_gen_v8_0
vlib msim/fifo_generator_v10_0
vlib msim/proc_common_v4_0
vlib msim/axi_datamover_v5_0
vlib msim/axi_sg_v4_04_a
vlib msim/axi_dma_v7_0
vlib msim/generic_baseblocks_v2_0
vlib msim/axi_infrastructure_v1_0
vlib msim/axi_register_slice_v2_0
vlib msim/axi_data_fifo_v2_0
vlib msim/axi_crossbar_v2_0

# Map libraries
vmap blk_mem_gen_v8_0 msim/blk_mem_gen_v8_0
vmap fifo_generator_v10_0 msim/fifo_generator_v10_0
vmap proc_common_v4_0 msim/proc_common_v4_0
vmap axi_datamover_v5_0 msim/axi_datamover_v5_0
vmap axi_sg_v4_04_a msim/axi_sg_v4_04_a
vmap axi_dma_v7_0 msim/axi_dma_v7_0
vmap generic_baseblocks_v2_0 msim/generic_baseblocks_v2_0
vmap axi_infrastructure_v1_0 msim/axi_infrastructure_v1_0
vmap axi_register_slice_v2_0 msim/axi_register_slice_v2_0
vmap axi_data_fifo_v2_0 msim/axi_data_fifo_v2_0
vmap axi_crossbar_v2_0 msim/axi_crossbar_v2_0

# Compile IPI sources
vlog  -work work  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_cdn_axi_bfm_1_0/hdl/src/verilog/design_1_cdn_axi_bfm_1_0.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vcom  -work blk_mem_gen_v8_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/blk_mem_gen_v8_0/simulation/blk_mem_gen_v8_0.vhd"
vcom  -work fifo_generator_v10_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/fifo_generator_v10_0/simulation/fifo_generator_v10_0.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/proc_common_v4_0/hdl/src/vhdl/family.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/proc_common_v4_0/hdl/src/vhdl/family_support.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/proc_common_v4_0/hdl/src/vhdl/coregen_comp_defs.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/proc_common_v4_0/hdl/src/vhdl/common_types_pkg.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/proc_common_v4_0/hdl/src/vhdl/proc_common_pkg.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/proc_common_v4_0/hdl/src/vhdl/conv_funs_pkg.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/proc_common_v4_0/hdl/src/vhdl/ipif_pkg.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/proc_common_v4_0/hdl/src/vhdl/async_fifo_fg.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/proc_common_v4_0/hdl/src/vhdl/sync_fifo_fg.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/proc_common_v4_0/hdl/src/vhdl/basic_sfifo_fg.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/proc_common_v4_0/hdl/src/vhdl/blk_mem_gen_wrapper.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/proc_common_v4_0/hdl/src/vhdl/addsub.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/proc_common_v4_0/hdl/src/vhdl/counter_bit.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/proc_common_v4_0/hdl/src/vhdl/counter.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/proc_common_v4_0/hdl/src/vhdl/direct_path_cntr.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/proc_common_v4_0/hdl/src/vhdl/direct_path_cntr_ai.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/proc_common_v4_0/hdl/src/vhdl/down_counter.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/proc_common_v4_0/hdl/src/vhdl/eval_timer.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/proc_common_v4_0/hdl/src/vhdl/inferred_lut4.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/proc_common_v4_0/hdl/src/vhdl/ipif_steer.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/proc_common_v4_0/hdl/src/vhdl/ipif_steer128.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/proc_common_v4_0/hdl/src/vhdl/ipif_mirror128.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/proc_common_v4_0/hdl/src/vhdl/ld_arith_reg.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/proc_common_v4_0/hdl/src/vhdl/ld_arith_reg2.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/proc_common_v4_0/hdl/src/vhdl/mux_onehot.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/proc_common_v4_0/hdl/src/vhdl/or_bits.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/proc_common_v4_0/hdl/src/vhdl/or_muxcy.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/proc_common_v4_0/hdl/src/vhdl/or_gate.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/proc_common_v4_0/hdl/src/vhdl/or_gate128.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/proc_common_v4_0/hdl/src/vhdl/pf_adder_bit.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/proc_common_v4_0/hdl/src/vhdl/pf_adder.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/proc_common_v4_0/hdl/src/vhdl/pf_counter_bit.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/proc_common_v4_0/hdl/src/vhdl/pf_counter.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/proc_common_v4_0/hdl/src/vhdl/pf_counter_top.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/proc_common_v4_0/hdl/src/vhdl/pf_occ_counter.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/proc_common_v4_0/hdl/src/vhdl/pf_occ_counter_top.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/proc_common_v4_0/hdl/src/vhdl/pf_dpram_select.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/proc_common_v4_0/hdl/src/vhdl/pselect.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/proc_common_v4_0/hdl/src/vhdl/pselect_mask.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/proc_common_v4_0/hdl/src/vhdl/srl16_fifo.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/proc_common_v4_0/hdl/src/vhdl/srl_fifo.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/proc_common_v4_0/hdl/src/vhdl/srl_fifo2.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/proc_common_v4_0/hdl/src/vhdl/srl_fifo3.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/proc_common_v4_0/hdl/src/vhdl/srl_fifo_rbu.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/proc_common_v4_0/hdl/src/vhdl/valid_be.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/proc_common_v4_0/hdl/src/vhdl/or_with_enable_f.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/proc_common_v4_0/hdl/src/vhdl/muxf_struct_f.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/proc_common_v4_0/hdl/src/vhdl/cntr_incr_decr_addn_f.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/proc_common_v4_0/hdl/src/vhdl/dynshreg_f.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/proc_common_v4_0/hdl/src/vhdl/dynshreg_i_f.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/proc_common_v4_0/hdl/src/vhdl/mux_onehot_f.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/proc_common_v4_0/hdl/src/vhdl/srl_fifo_rbu_f.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/proc_common_v4_0/hdl/src/vhdl/srl_fifo_f.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/proc_common_v4_0/hdl/src/vhdl/compare_vectors_f.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/proc_common_v4_0/hdl/src/vhdl/pselect_f.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/proc_common_v4_0/hdl/src/vhdl/counter_f.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/proc_common_v4_0/hdl/src/vhdl/or_muxcy_f.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/proc_common_v4_0/hdl/src/vhdl/or_gate_f.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/proc_common_v4_0/hdl/src/vhdl/soft_reset.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_reset.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_afifo_autord.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_sfifo_autord.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_fifo.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_cmd_status.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_scc.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_strb_gen2.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_pcc.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_addr_cntl.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_rdmux.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_rddata_cntl.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_rd_status_cntl.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_wr_demux.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_wrdata_cntl.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_wr_status_cntl.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_skid2mm_buf.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_skid_buf.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_rd_sf.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_wr_sf.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_stbs_set.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_stbs_set_nodre.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_ibttcc.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_indet_btt.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_dre_mux2_1_x_n.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_dre_mux4_1_x_n.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_dre_mux8_1_x_n.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_mm2s_dre.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_s2mm_dre.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_ms_strb_set.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_mssai_skid_buf.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_slice.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_s2mm_scatter.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_s2mm_realign.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_s2mm_basic_wrap.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_s2mm_omit_wrap.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_s2mm_full_wrap.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_mm2s_basic_wrap.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_mm2s_omit_wrap.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_mm2s_full_wrap.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_pkg.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_reset.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_sfifo_autord.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_afifo_autord.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_fifo.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_cmd_status.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_rdmux.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_addr_cntl.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_rddata_cntl.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_rd_status_cntl.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_scc.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_wr_demux.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_scc_wr.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_skid2mm_buf.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_wrdata_cntl.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_wr_status_cntl.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_skid_buf.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_mm2s_basic_wrap.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_s2mm_basic_wrap.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_datamover.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_ftch_sm.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_ftch_pntr.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_ftch_cmdsts_if.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_ftch_mngr.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_cntrl_strm.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_ftch_queue.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_ftch_noqueue.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_ftch_q_mngr.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_updt_cmdsts_if.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_updt_sm.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_updt_mngr.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_updt_queue.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_updt_noqueue.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_updt_q_mngr.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_intrpt.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg.vhd"
vcom  -work axi_dma_v7_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_dma_v7_0/hdl/src/vhdl/axi_dma_pkg.vhd"
vcom  -work axi_dma_v7_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_dma_v7_0/hdl/src/vhdl/axi_dma_reset.vhd"
vcom  -work axi_dma_v7_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_dma_v7_0/hdl/src/vhdl/axi_dma_rst_module.vhd"
vcom  -work axi_dma_v7_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_dma_v7_0/hdl/src/vhdl/axi_dma_lite_if.vhd"
vcom  -work axi_dma_v7_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_dma_v7_0/hdl/src/vhdl/axi_dma_register.vhd"
vcom  -work axi_dma_v7_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_dma_v7_0/hdl/src/vhdl/axi_dma_register_s2mm.vhd"
vcom  -work axi_dma_v7_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_dma_v7_0/hdl/src/vhdl/axi_dma_reg_module.vhd"
vcom  -work axi_dma_v7_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_dma_v7_0/hdl/src/vhdl/axi_dma_skid_buf.vhd"
vcom  -work axi_dma_v7_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_dma_v7_0/hdl/src/vhdl/axi_dma_afifo_autord.vhd"
vcom  -work axi_dma_v7_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_dma_v7_0/hdl/src/vhdl/axi_dma_s2mm.vhd"
vcom  -work axi_dma_v7_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_dma_v7_0/hdl/src/vhdl/axi_dma_sofeof_gen.vhd"
vcom  -work axi_dma_v7_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_dma_v7_0/hdl/src/vhdl/axi_dma_smple_sm.vhd"
vcom  -work axi_dma_v7_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_dma_v7_0/hdl/src/vhdl/axi_dma_mm2s_sg_if.vhd"
vcom  -work axi_dma_v7_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_dma_v7_0/hdl/src/vhdl/axi_dma_mm2s_sm.vhd"
vcom  -work axi_dma_v7_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_dma_v7_0/hdl/src/vhdl/axi_dma_mm2s_cmdsts_if.vhd"
vcom  -work axi_dma_v7_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_dma_v7_0/hdl/src/vhdl/axi_dma_mm2s_sts_mngr.vhd"
vcom  -work axi_dma_v7_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_dma_v7_0/hdl/src/vhdl/axi_dma_mm2s_cntrl_strm.vhd"
vcom  -work axi_dma_v7_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_dma_v7_0/hdl/src/vhdl/axi_dma_mm2s_mngr.vhd"
vcom  -work axi_dma_v7_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_dma_v7_0/hdl/src/vhdl/axi_dma_s2mm_sg_if.vhd"
vcom  -work axi_dma_v7_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_dma_v7_0/hdl/src/vhdl/axi_dma_s2mm_sm.vhd"
vcom  -work axi_dma_v7_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_dma_v7_0/hdl/src/vhdl/axi_dma_s2mm_cmdsts_if.vhd"
vcom  -work axi_dma_v7_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_dma_v7_0/hdl/src/vhdl/axi_dma_s2mm_sts_mngr.vhd"
vcom  -work axi_dma_v7_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_dma_v7_0/hdl/src/vhdl/axi_dma_s2mm_sts_strm.vhd"
vcom  -work axi_dma_v7_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_dma_v7_0/hdl/src/vhdl/axi_dma_s2mm_mngr.vhd"
vcom  -work axi_dma_v7_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_dma_v7_0/hdl/src/vhdl/axi_dma_cmd_split.vhd"
vcom  -work axi_dma_v7_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/axi_dma_v7_0/hdl/src/vhdl/axi_dma.vhd"
vcom  -work work -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/sim/design_1_axi_dma_1_0.vhd"
vlog  -work generic_baseblocks_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/generic_baseblocks_v2_0/hdl/verilog/generic_baseblocks_v2_0_carry_and.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work generic_baseblocks_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/generic_baseblocks_v2_0/hdl/verilog/generic_baseblocks_v2_0_carry_latch_and.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work generic_baseblocks_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/generic_baseblocks_v2_0/hdl/verilog/generic_baseblocks_v2_0_carry_latch_or.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work generic_baseblocks_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/generic_baseblocks_v2_0/hdl/verilog/generic_baseblocks_v2_0_carry_or.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work generic_baseblocks_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/generic_baseblocks_v2_0/hdl/verilog/generic_baseblocks_v2_0_carry.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work generic_baseblocks_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/generic_baseblocks_v2_0/hdl/verilog/generic_baseblocks_v2_0_command_fifo.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work generic_baseblocks_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/generic_baseblocks_v2_0/hdl/verilog/generic_baseblocks_v2_0_comparator_mask_static.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work generic_baseblocks_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/generic_baseblocks_v2_0/hdl/verilog/generic_baseblocks_v2_0_comparator_mask.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work generic_baseblocks_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/generic_baseblocks_v2_0/hdl/verilog/generic_baseblocks_v2_0_comparator_sel_mask_static.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work generic_baseblocks_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/generic_baseblocks_v2_0/hdl/verilog/generic_baseblocks_v2_0_comparator_sel_mask.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work generic_baseblocks_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/generic_baseblocks_v2_0/hdl/verilog/generic_baseblocks_v2_0_comparator_sel_static.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work generic_baseblocks_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/generic_baseblocks_v2_0/hdl/verilog/generic_baseblocks_v2_0_comparator_sel.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work generic_baseblocks_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/generic_baseblocks_v2_0/hdl/verilog/generic_baseblocks_v2_0_comparator_static.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work generic_baseblocks_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/generic_baseblocks_v2_0/hdl/verilog/generic_baseblocks_v2_0_comparator.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work generic_baseblocks_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/generic_baseblocks_v2_0/hdl/verilog/generic_baseblocks_v2_0_mux_enc.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work generic_baseblocks_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/generic_baseblocks_v2_0/hdl/verilog/generic_baseblocks_v2_0_mux.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work generic_baseblocks_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/generic_baseblocks_v2_0/hdl/verilog/generic_baseblocks_v2_0_nto1_mux.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work axi_infrastructure_v1_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog/axi_infrastructure_v1_0_axi2vector.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work axi_infrastructure_v1_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog/axi_infrastructure_v1_0_axic_srl_fifo.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work axi_infrastructure_v1_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog/axi_infrastructure_v1_0_vector2axi.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work axi_register_slice_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_register_slice_v2_0/hdl/verilog/axi_register_slice_v2_0_axic_register_slice.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work axi_register_slice_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_register_slice_v2_0/hdl/verilog/axi_register_slice_v2_0_axi_register_slice.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work fifo_generator_v10_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/fifo_generator_v10_0/simulation/fifo_generator_v10_0.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work axi_data_fifo_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_data_fifo_v2_0/hdl/verilog/axi_data_fifo_v2_0_axic_fifo.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work axi_data_fifo_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_data_fifo_v2_0/hdl/verilog/axi_data_fifo_v2_0_fifo_gen.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work axi_data_fifo_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_data_fifo_v2_0/hdl/verilog/axi_data_fifo_v2_0_axic_srl_fifo.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work axi_data_fifo_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_data_fifo_v2_0/hdl/verilog/axi_data_fifo_v2_0_axic_reg_srl_fifo.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work axi_data_fifo_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_data_fifo_v2_0/hdl/verilog/axi_data_fifo_v2_0_ndeep_srl.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work axi_data_fifo_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_data_fifo_v2_0/hdl/verilog/axi_data_fifo_v2_0_axi_data_fifo.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work axi_crossbar_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_crossbar_v2_0/hdl/verilog/axi_crossbar_v2_0_addr_arbiter_sasd.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work axi_crossbar_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_crossbar_v2_0/hdl/verilog/axi_crossbar_v2_0_addr_arbiter.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work axi_crossbar_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_crossbar_v2_0/hdl/verilog/axi_crossbar_v2_0_addr_decoder.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work axi_crossbar_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_crossbar_v2_0/hdl/verilog/axi_crossbar_v2_0_arbiter_resp.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work axi_crossbar_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_crossbar_v2_0/hdl/verilog/axi_crossbar_v2_0_crossbar_sasd.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work axi_crossbar_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_crossbar_v2_0/hdl/verilog/axi_crossbar_v2_0_crossbar.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work axi_crossbar_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_crossbar_v2_0/hdl/verilog/axi_crossbar_v2_0_decerr_slave.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work axi_crossbar_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_crossbar_v2_0/hdl/verilog/axi_crossbar_v2_0_si_transactor.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work axi_crossbar_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_crossbar_v2_0/hdl/verilog/axi_crossbar_v2_0_splitter.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work axi_crossbar_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_crossbar_v2_0/hdl/verilog/axi_crossbar_v2_0_wdata_mux.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work axi_crossbar_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_crossbar_v2_0/hdl/verilog/axi_crossbar_v2_0_wdata_router.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work axi_crossbar_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_crossbar_v2_0/hdl/verilog/axi_crossbar_v2_0_axi_crossbar.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work work  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/sim/design_1_xbar_0.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work generic_baseblocks_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/generic_baseblocks_v2_0/hdl/verilog/generic_baseblocks_v2_0_carry_and.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work generic_baseblocks_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/generic_baseblocks_v2_0/hdl/verilog/generic_baseblocks_v2_0_carry_latch_and.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work generic_baseblocks_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/generic_baseblocks_v2_0/hdl/verilog/generic_baseblocks_v2_0_carry_latch_or.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work generic_baseblocks_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/generic_baseblocks_v2_0/hdl/verilog/generic_baseblocks_v2_0_carry_or.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work generic_baseblocks_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/generic_baseblocks_v2_0/hdl/verilog/generic_baseblocks_v2_0_carry.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work generic_baseblocks_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/generic_baseblocks_v2_0/hdl/verilog/generic_baseblocks_v2_0_command_fifo.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work generic_baseblocks_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/generic_baseblocks_v2_0/hdl/verilog/generic_baseblocks_v2_0_comparator_mask_static.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work generic_baseblocks_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/generic_baseblocks_v2_0/hdl/verilog/generic_baseblocks_v2_0_comparator_mask.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work generic_baseblocks_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/generic_baseblocks_v2_0/hdl/verilog/generic_baseblocks_v2_0_comparator_sel_mask_static.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work generic_baseblocks_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/generic_baseblocks_v2_0/hdl/verilog/generic_baseblocks_v2_0_comparator_sel_mask.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work generic_baseblocks_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/generic_baseblocks_v2_0/hdl/verilog/generic_baseblocks_v2_0_comparator_sel_static.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work generic_baseblocks_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/generic_baseblocks_v2_0/hdl/verilog/generic_baseblocks_v2_0_comparator_sel.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work generic_baseblocks_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/generic_baseblocks_v2_0/hdl/verilog/generic_baseblocks_v2_0_comparator_static.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work generic_baseblocks_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/generic_baseblocks_v2_0/hdl/verilog/generic_baseblocks_v2_0_comparator.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work generic_baseblocks_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/generic_baseblocks_v2_0/hdl/verilog/generic_baseblocks_v2_0_mux_enc.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work generic_baseblocks_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/generic_baseblocks_v2_0/hdl/verilog/generic_baseblocks_v2_0_mux.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work generic_baseblocks_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/generic_baseblocks_v2_0/hdl/verilog/generic_baseblocks_v2_0_nto1_mux.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work axi_infrastructure_v1_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog/axi_infrastructure_v1_0_axi2vector.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work axi_infrastructure_v1_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog/axi_infrastructure_v1_0_axic_srl_fifo.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work axi_infrastructure_v1_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog/axi_infrastructure_v1_0_vector2axi.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work axi_register_slice_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_register_slice_v2_0/hdl/verilog/axi_register_slice_v2_0_axic_register_slice.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work axi_register_slice_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_register_slice_v2_0/hdl/verilog/axi_register_slice_v2_0_axi_register_slice.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work fifo_generator_v10_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/fifo_generator_v10_0/simulation/fifo_generator_v10_0.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work axi_data_fifo_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_data_fifo_v2_0/hdl/verilog/axi_data_fifo_v2_0_axic_fifo.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work axi_data_fifo_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_data_fifo_v2_0/hdl/verilog/axi_data_fifo_v2_0_fifo_gen.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work axi_data_fifo_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_data_fifo_v2_0/hdl/verilog/axi_data_fifo_v2_0_axic_srl_fifo.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work axi_data_fifo_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_data_fifo_v2_0/hdl/verilog/axi_data_fifo_v2_0_axic_reg_srl_fifo.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work axi_data_fifo_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_data_fifo_v2_0/hdl/verilog/axi_data_fifo_v2_0_ndeep_srl.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work axi_data_fifo_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_data_fifo_v2_0/hdl/verilog/axi_data_fifo_v2_0_axi_data_fifo.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work axi_crossbar_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_crossbar_v2_0/hdl/verilog/axi_crossbar_v2_0_addr_arbiter_sasd.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work axi_crossbar_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_crossbar_v2_0/hdl/verilog/axi_crossbar_v2_0_addr_arbiter.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work axi_crossbar_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_crossbar_v2_0/hdl/verilog/axi_crossbar_v2_0_addr_decoder.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work axi_crossbar_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_crossbar_v2_0/hdl/verilog/axi_crossbar_v2_0_arbiter_resp.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work axi_crossbar_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_crossbar_v2_0/hdl/verilog/axi_crossbar_v2_0_crossbar_sasd.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work axi_crossbar_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_crossbar_v2_0/hdl/verilog/axi_crossbar_v2_0_crossbar.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work axi_crossbar_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_crossbar_v2_0/hdl/verilog/axi_crossbar_v2_0_decerr_slave.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work axi_crossbar_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_crossbar_v2_0/hdl/verilog/axi_crossbar_v2_0_si_transactor.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work axi_crossbar_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_crossbar_v2_0/hdl/verilog/axi_crossbar_v2_0_splitter.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work axi_crossbar_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_crossbar_v2_0/hdl/verilog/axi_crossbar_v2_0_wdata_mux.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work axi_crossbar_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_crossbar_v2_0/hdl/verilog/axi_crossbar_v2_0_wdata_router.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work axi_crossbar_v2_0  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_crossbar_v2_0/hdl/verilog/axi_crossbar_v2_0_axi_crossbar.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work work  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/sim/design_1_xbar_1.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vcom  -work blk_mem_gen_v8_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/blk_mem_gen_v8_0/simulation/blk_mem_gen_v8_0.vhd"
vcom  -work fifo_generator_v10_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/fifo_generator_v10_0/simulation/fifo_generator_v10_0.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/proc_common_v4_0/hdl/src/vhdl/family.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/proc_common_v4_0/hdl/src/vhdl/family_support.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/proc_common_v4_0/hdl/src/vhdl/coregen_comp_defs.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/proc_common_v4_0/hdl/src/vhdl/common_types_pkg.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/proc_common_v4_0/hdl/src/vhdl/proc_common_pkg.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/proc_common_v4_0/hdl/src/vhdl/conv_funs_pkg.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/proc_common_v4_0/hdl/src/vhdl/ipif_pkg.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/proc_common_v4_0/hdl/src/vhdl/async_fifo_fg.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/proc_common_v4_0/hdl/src/vhdl/sync_fifo_fg.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/proc_common_v4_0/hdl/src/vhdl/basic_sfifo_fg.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/proc_common_v4_0/hdl/src/vhdl/blk_mem_gen_wrapper.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/proc_common_v4_0/hdl/src/vhdl/addsub.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/proc_common_v4_0/hdl/src/vhdl/counter_bit.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/proc_common_v4_0/hdl/src/vhdl/counter.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/proc_common_v4_0/hdl/src/vhdl/direct_path_cntr.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/proc_common_v4_0/hdl/src/vhdl/direct_path_cntr_ai.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/proc_common_v4_0/hdl/src/vhdl/down_counter.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/proc_common_v4_0/hdl/src/vhdl/eval_timer.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/proc_common_v4_0/hdl/src/vhdl/inferred_lut4.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/proc_common_v4_0/hdl/src/vhdl/ipif_steer.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/proc_common_v4_0/hdl/src/vhdl/ipif_steer128.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/proc_common_v4_0/hdl/src/vhdl/ipif_mirror128.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/proc_common_v4_0/hdl/src/vhdl/ld_arith_reg.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/proc_common_v4_0/hdl/src/vhdl/ld_arith_reg2.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/proc_common_v4_0/hdl/src/vhdl/mux_onehot.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/proc_common_v4_0/hdl/src/vhdl/or_bits.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/proc_common_v4_0/hdl/src/vhdl/or_muxcy.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/proc_common_v4_0/hdl/src/vhdl/or_gate.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/proc_common_v4_0/hdl/src/vhdl/or_gate128.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/proc_common_v4_0/hdl/src/vhdl/pf_adder_bit.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/proc_common_v4_0/hdl/src/vhdl/pf_adder.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/proc_common_v4_0/hdl/src/vhdl/pf_counter_bit.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/proc_common_v4_0/hdl/src/vhdl/pf_counter.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/proc_common_v4_0/hdl/src/vhdl/pf_counter_top.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/proc_common_v4_0/hdl/src/vhdl/pf_occ_counter.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/proc_common_v4_0/hdl/src/vhdl/pf_occ_counter_top.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/proc_common_v4_0/hdl/src/vhdl/pf_dpram_select.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/proc_common_v4_0/hdl/src/vhdl/pselect.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/proc_common_v4_0/hdl/src/vhdl/pselect_mask.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/proc_common_v4_0/hdl/src/vhdl/srl16_fifo.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/proc_common_v4_0/hdl/src/vhdl/srl_fifo.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/proc_common_v4_0/hdl/src/vhdl/srl_fifo2.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/proc_common_v4_0/hdl/src/vhdl/srl_fifo3.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/proc_common_v4_0/hdl/src/vhdl/srl_fifo_rbu.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/proc_common_v4_0/hdl/src/vhdl/valid_be.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/proc_common_v4_0/hdl/src/vhdl/or_with_enable_f.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/proc_common_v4_0/hdl/src/vhdl/muxf_struct_f.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/proc_common_v4_0/hdl/src/vhdl/cntr_incr_decr_addn_f.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/proc_common_v4_0/hdl/src/vhdl/dynshreg_f.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/proc_common_v4_0/hdl/src/vhdl/dynshreg_i_f.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/proc_common_v4_0/hdl/src/vhdl/mux_onehot_f.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/proc_common_v4_0/hdl/src/vhdl/srl_fifo_rbu_f.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/proc_common_v4_0/hdl/src/vhdl/srl_fifo_f.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/proc_common_v4_0/hdl/src/vhdl/compare_vectors_f.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/proc_common_v4_0/hdl/src/vhdl/pselect_f.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/proc_common_v4_0/hdl/src/vhdl/counter_f.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/proc_common_v4_0/hdl/src/vhdl/or_muxcy_f.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/proc_common_v4_0/hdl/src/vhdl/or_gate_f.vhd"
vcom  -work proc_common_v4_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/proc_common_v4_0/hdl/src/vhdl/soft_reset.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_reset.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_afifo_autord.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_sfifo_autord.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_fifo.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_cmd_status.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_scc.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_strb_gen2.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_pcc.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_addr_cntl.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_rdmux.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_rddata_cntl.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_rd_status_cntl.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_wr_demux.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_wrdata_cntl.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_wr_status_cntl.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_skid2mm_buf.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_skid_buf.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_rd_sf.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_wr_sf.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_stbs_set.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_stbs_set_nodre.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_ibttcc.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_indet_btt.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_dre_mux2_1_x_n.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_dre_mux4_1_x_n.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_dre_mux8_1_x_n.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_mm2s_dre.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_s2mm_dre.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_ms_strb_set.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_mssai_skid_buf.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_slice.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_s2mm_scatter.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_s2mm_realign.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_s2mm_basic_wrap.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_s2mm_omit_wrap.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_s2mm_full_wrap.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_mm2s_basic_wrap.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_mm2s_omit_wrap.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover_mm2s_full_wrap.vhd"
vcom  -work axi_datamover_v5_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_datamover_v5_0/hdl/src/vhdl/axi_datamover.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_pkg.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_reset.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_sfifo_autord.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_afifo_autord.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_fifo.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_cmd_status.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_rdmux.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_addr_cntl.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_rddata_cntl.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_rd_status_cntl.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_scc.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_wr_demux.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_scc_wr.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_skid2mm_buf.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_wrdata_cntl.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_wr_status_cntl.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_skid_buf.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_mm2s_basic_wrap.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_s2mm_basic_wrap.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_datamover.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_ftch_sm.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_ftch_pntr.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_ftch_cmdsts_if.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_ftch_mngr.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_cntrl_strm.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_ftch_queue.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_ftch_noqueue.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_ftch_q_mngr.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_updt_cmdsts_if.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_updt_sm.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_updt_mngr.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_updt_queue.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_updt_noqueue.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_updt_q_mngr.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg_intrpt.vhd"
vcom  -work axi_sg_v4_04_a -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_sg_v4_04_a/hdl/src/vhdl/axi_sg.vhd"
vcom  -work axi_dma_v7_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_dma_v7_0/hdl/src/vhdl/axi_dma_pkg.vhd"
vcom  -work axi_dma_v7_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_dma_v7_0/hdl/src/vhdl/axi_dma_reset.vhd"
vcom  -work axi_dma_v7_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_dma_v7_0/hdl/src/vhdl/axi_dma_rst_module.vhd"
vcom  -work axi_dma_v7_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_dma_v7_0/hdl/src/vhdl/axi_dma_lite_if.vhd"
vcom  -work axi_dma_v7_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_dma_v7_0/hdl/src/vhdl/axi_dma_register.vhd"
vcom  -work axi_dma_v7_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_dma_v7_0/hdl/src/vhdl/axi_dma_register_s2mm.vhd"
vcom  -work axi_dma_v7_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_dma_v7_0/hdl/src/vhdl/axi_dma_reg_module.vhd"
vcom  -work axi_dma_v7_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_dma_v7_0/hdl/src/vhdl/axi_dma_skid_buf.vhd"
vcom  -work axi_dma_v7_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_dma_v7_0/hdl/src/vhdl/axi_dma_afifo_autord.vhd"
vcom  -work axi_dma_v7_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_dma_v7_0/hdl/src/vhdl/axi_dma_s2mm.vhd"
vcom  -work axi_dma_v7_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_dma_v7_0/hdl/src/vhdl/axi_dma_sofeof_gen.vhd"
vcom  -work axi_dma_v7_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_dma_v7_0/hdl/src/vhdl/axi_dma_smple_sm.vhd"
vcom  -work axi_dma_v7_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_dma_v7_0/hdl/src/vhdl/axi_dma_mm2s_sg_if.vhd"
vcom  -work axi_dma_v7_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_dma_v7_0/hdl/src/vhdl/axi_dma_mm2s_sm.vhd"
vcom  -work axi_dma_v7_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_dma_v7_0/hdl/src/vhdl/axi_dma_mm2s_cmdsts_if.vhd"
vcom  -work axi_dma_v7_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_dma_v7_0/hdl/src/vhdl/axi_dma_mm2s_sts_mngr.vhd"
vcom  -work axi_dma_v7_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_dma_v7_0/hdl/src/vhdl/axi_dma_mm2s_cntrl_strm.vhd"
vcom  -work axi_dma_v7_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_dma_v7_0/hdl/src/vhdl/axi_dma_mm2s_mngr.vhd"
vcom  -work axi_dma_v7_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_dma_v7_0/hdl/src/vhdl/axi_dma_s2mm_sg_if.vhd"
vcom  -work axi_dma_v7_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_dma_v7_0/hdl/src/vhdl/axi_dma_s2mm_sm.vhd"
vcom  -work axi_dma_v7_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_dma_v7_0/hdl/src/vhdl/axi_dma_s2mm_cmdsts_if.vhd"
vcom  -work axi_dma_v7_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_dma_v7_0/hdl/src/vhdl/axi_dma_s2mm_sts_mngr.vhd"
vcom  -work axi_dma_v7_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_dma_v7_0/hdl/src/vhdl/axi_dma_s2mm_sts_strm.vhd"
vcom  -work axi_dma_v7_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_dma_v7_0/hdl/src/vhdl/axi_dma_s2mm_mngr.vhd"
vcom  -work axi_dma_v7_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_dma_v7_0/hdl/src/vhdl/axi_dma_cmd_split.vhd"
vcom  -work axi_dma_v7_0 -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/axi_dma_v7_0/hdl/src/vhdl/axi_dma.vhd"
vcom  -work work -93 "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_1/sim/design_1_axi_dma_2_1.vhd"
vlog  -work work  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_cdn_axi_bfm_2_1/hdl/src/verilog/design_1_cdn_axi_bfm_2_1.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work work  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/hdl/design_1.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog
vlog  -work work  "../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/imports/hdl/design_1_wrapper.v" +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/axi_infrastructure_v1_0/hdl/verilog +incdir+../proj/dma_sim_v1_0/dma_sim_v1_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/axi_infrastructure_v1_0/hdl/verilog

# Compile source files
vlog -work work "../src/dma_sim_v1_0_top.v"
vlog -work work "../tb/dma_sim_v1_0_top_tb.v"

# Add global set/reset
vlog -work work "C:/Xilinx/Vivado/2013.2/data/verilog/src/glbl.v"

