domain_path: /home/nothon/fpga2C/vitis_workspace/zturnV2_platform/export/zturnV2_platform/sw/ps7_standalone
app_src_dir: /tools/Xilinx/Vitis/2024.1/data/embeddedsw/lib/sw_apps/empty_application
template: empty_application
