set_property SRC_FILE_INFO {cfile:C:/Projects/A_Series_7/LvdsSerialAdc/Projects/Adc_Interface/Constraints/KC705_AdcToplevel_Toplevel.xdc rfile:../../../../../Constraints/KC705_AdcToplevel_Toplevel.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
create_pblock Apps_AdcToplevel
add_cells_to_pblock [get_pblocks Apps_AdcToplevel] [get_cells -quiet [list AdcToplevel_Toplevel_I_AdcToplevel]]
resize_pblock [get_pblocks Apps_AdcToplevel] -add {SLICE_X0Y60:SLICE_X7Y89}
set_property src_info {type:XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_pin  AE30 [get_ports DATA_p_pin[0]]
set_property src_info {type:XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_pin  AF30 [get_ports DATA_n_pin[0]]
set_property src_info {type:XDC file:1 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_pin  AJ28 [get_ports DATA_p_pin[2]]
set_property src_info {type:XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_pin  AJ29 [get_ports DATA_n_pin[2]]
set_property src_info {type:XDC file:1 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_pin  AD27 [get_ports FCLK_p_pin]
set_property src_info {type:XDC file:1 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_pin  AD28 [get_ports FCLK_n_pin]
set_property src_info {type:XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_pin  AB27 [get_ports DCLK_p_pin]
set_property src_info {type:XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_pin  AC27 [get_ports DCLK_n_pin]
set_property src_info {type:XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_pin  AC29 [get_ports DATA_p_pin[1]]
set_property src_info {type:XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_pin  AC30 [get_ports DATA_n_pin[1]]
set_property src_info {type:XDC file:1 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_pin  Y30  [get_ports DATA_p_pin[3]]
set_property src_info {type:XDC file:1 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_pin  AA30 [get_ports DATA_n_pin[3]]
