set_property SRC_FILE_INFO {cfile:C:/Projects/A_Series_7/LvdsSerialAdc/Projects/Adc_Interface/Constraints/KC705_Apps_AdcToplevel.xdc rfile:../../../../../Constraints/KC705_Apps_AdcToplevel.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
create_pblock Apps_AdcToplevel
add_cells_to_pblock [get_pblocks Apps_AdcToplevel] [get_cells -quiet [list Apps_AdcToplevel_I_AdcToplevel]]
resize_pblock [get_pblocks Apps_AdcToplevel] -add {SLICE_X0Y60:SLICE_X7Y89}
set_property src_info {type:XDC file:1 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  L25  [get_ports Sys_Clk_p_pin]
set_property src_info {type:XDC file:1 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  K25  [get_ports Sys_Clk_n_pin]
set_property src_info {type:XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AE26 [get_ports AdcIntrfcStats_pin[3]]
set_property src_info {type:XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  G19  [get_ports AdcIntrfcStats_pin[2]]
set_property src_info {type:XDC file:1 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  E18  [get_ports AdcIntrfcStats_pin[1]]
set_property src_info {type:XDC file:1 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  F16  [get_ports AdcIntrfcStats_pin[0]]
set_property src_info {type:XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AA12 [get_ports Adc_ReSync_pin]
set_property src_info {type:XDC file:1 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AC29 [get_ports Adc_DI_1_0_p_pin]
set_property src_info {type:XDC file:1 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AC30 [get_ports Adc_DI_1_0_n_pin]
set_property src_info {type:XDC file:1 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  Y30  [get_ports Adc_DI_3_0_p_pin]
set_property src_info {type:XDC file:1 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AA30 [get_ports Adc_DI_3_0_n_pin]
set_property src_info {type:XDC file:1 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AD27 [get_ports Adc_FCLK_0_p_pin]
set_property src_info {type:XDC file:1 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AD28 [get_ports Adc_FCLK_0_n_pin]
set_property src_info {type:XDC file:1 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AB27 [get_ports Adc_DCLK_0_p_pin]
set_property src_info {type:XDC file:1 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AC27 [get_ports Adc_DCLK_0_n_pin]
set_property src_info {type:XDC file:1 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AE30 [get_ports Adc_DI_0_0_p_pin]
set_property src_info {type:XDC file:1 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AF30 [get_ports Adc_DI_0_0_n_pin]
set_property src_info {type:XDC file:1 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AJ28 [get_ports Adc_DI_2_0_p_pin]
set_property src_info {type:XDC file:1 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AJ29 [get_ports Adc_DI_2_0_n_pin]
set_property src_info {type:XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  B30  [get_ports AdcFrmDataOut_pin[15]]
set_property src_info {type:XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  A30  [get_ports AdcFrmDataOut_pin[14]]
set_property src_info {type:XDC file:1 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  E29  [get_ports AdcFrmDataOut_pin[13]]
set_property src_info {type:XDC file:1 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  E30  [get_ports AdcFrmDataOut_pin[12]]
set_property src_info {type:XDC file:1 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  H24  [get_ports AdcFrmDataOut_pin[11]]
set_property src_info {type:XDC file:1 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  H25  [get_ports AdcFrmDataOut_pin[10]]
set_property src_info {type:XDC file:1 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  G28  [get_ports AdcFrmDataOut_pin[9]]
set_property src_info {type:XDC file:1 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  F28  [get_ports AdcFrmDataOut_pin[8]]
set_property src_info {type:XDC file:1 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  G27  [get_ports AdcFrmDataOut_pin[7]]
set_property src_info {type:XDC file:1 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  F27  [get_ports AdcFrmDataOut_pin[6]]
set_property src_info {type:XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  G29  [get_ports AdcFrmDataOut_pin[5]]
set_property src_info {type:XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  F30  [get_ports AdcFrmDataOut_pin[4]]
set_property src_info {type:XDC file:1 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  H26  [get_ports AdcFrmDataOut_pin[3]]
set_property src_info {type:XDC file:1 line:189 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  H27  [get_ports AdcFrmDataOut_pin[2]]
set_property src_info {type:XDC file:1 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  H30  [get_ports AdcFrmDataOut_pin[1]]
set_property src_info {type:XDC file:1 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  G30  [get_ports AdcFrmDataOut_pin[0]]
set_property src_info {type:XDC file:1 line:211 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  G18   [get_ports AdcMemDataOut_pin[17]]
set_property src_info {type:XDC file:1 line:212 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  F18   [get_ports AdcMemDataOut_pin[16]]
set_property src_info {type:XDC file:1 line:213 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  C17   [get_ports AdcMemDataOut_pin[15]]
set_property src_info {type:XDC file:1 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  B17   [get_ports AdcMemDataOut_pin[14]]
set_property src_info {type:XDC file:1 line:215 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  G17   [get_ports AdcMemDataOut_pin[13]]
set_property src_info {type:XDC file:1 line:216 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  F17   [get_ports AdcMemDataOut_pin[12]]
set_property src_info {type:XDC file:1 line:217 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  C20   [get_ports AdcMemDataOut_pin[11]]
set_property src_info {type:XDC file:1 line:218 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  B20   [get_ports AdcMemDataOut_pin[10]]
set_property src_info {type:XDC file:1 line:219 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  A16   [get_ports AdcMemDataOut_pin[9]]
set_property src_info {type:XDC file:1 line:220 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  A17   [get_ports AdcMemDataOut_pin[8]]
set_property src_info {type:XDC file:1 line:221 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  A20   [get_ports AdcMemDataOut_pin[7]]
set_property src_info {type:XDC file:1 line:222 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  A21   [get_ports AdcMemDataOut_pin[6]]
set_property src_info {type:XDC file:1 line:223 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  B18   [get_ports AdcMemDataOut_pin[5]]
set_property src_info {type:XDC file:1 line:224 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  A18   [get_ports AdcMemDataOut_pin[4]]
set_property src_info {type:XDC file:1 line:225 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  B22   [get_ports AdcMemDataOut_pin[3]]
set_property src_info {type:XDC file:1 line:226 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  A22   [get_ports AdcMemDataOut_pin[2]]
set_property src_info {type:XDC file:1 line:227 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  C19   [get_ports AdcMemDataOut_pin[1]]
set_property src_info {type:XDC file:1 line:228 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  B19   [get_ports AdcMemDataOut_pin[0]]
