-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity main_design_v_mix_0_0_v_mix_upsample_false_9 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    srcLayer1Rgb_dout : IN STD_LOGIC_VECTOR (23 downto 0);
    srcLayer1Rgb_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    srcLayer1Rgb_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    srcLayer1Rgb_empty_n : IN STD_LOGIC;
    srcLayer1Rgb_read : OUT STD_LOGIC;
    HwReg_layerHeight_1_val_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    HwReg_layerHeight_1_val_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    HwReg_layerHeight_1_val_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    HwReg_layerHeight_1_val_empty_n : IN STD_LOGIC;
    HwReg_layerHeight_1_val_read : OUT STD_LOGIC;
    HwReg_layerWidth_1_val_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    HwReg_layerWidth_1_val_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    HwReg_layerWidth_1_val_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    HwReg_layerWidth_1_val_empty_n : IN STD_LOGIC;
    HwReg_layerWidth_1_val_read : OUT STD_LOGIC;
    HwReg_layerEnableFlag_1_val_dout : IN STD_LOGIC_VECTOR (0 downto 0);
    HwReg_layerEnableFlag_1_val_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    HwReg_layerEnableFlag_1_val_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    HwReg_layerEnableFlag_1_val_empty_n : IN STD_LOGIC;
    HwReg_layerEnableFlag_1_val_read : OUT STD_LOGIC;
    srcLayer1x_din : OUT STD_LOGIC_VECTOR (23 downto 0);
    srcLayer1x_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    srcLayer1x_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    srcLayer1x_full_n : IN STD_LOGIC;
    srcLayer1x_write : OUT STD_LOGIC;
    HwReg_layerWidth_1_val_c_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    HwReg_layerWidth_1_val_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    HwReg_layerWidth_1_val_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    HwReg_layerWidth_1_val_c_full_n : IN STD_LOGIC;
    HwReg_layerWidth_1_val_c_write : OUT STD_LOGIC;
    HwReg_layerHeight_1_val_c_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    HwReg_layerHeight_1_val_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    HwReg_layerHeight_1_val_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    HwReg_layerHeight_1_val_c_full_n : IN STD_LOGIC;
    HwReg_layerHeight_1_val_c_write : OUT STD_LOGIC );
end;


architecture behav of main_design_v_mix_0_0_v_mix_upsample_false_9 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal HwReg_layerHeight_1_val_blk_n : STD_LOGIC;
    signal HwReg_layerWidth_1_val_blk_n : STD_LOGIC;
    signal HwReg_layerEnableFlag_1_val_blk_n : STD_LOGIC;
    signal HwReg_layerWidth_1_val_c_blk_n : STD_LOGIC;
    signal HwReg_layerHeight_1_val_c_blk_n : STD_LOGIC;
    signal HwReg_layerEnableFlag_1_val_read_read_fu_92_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal HwReg_layerEnableFlag_1_val_read_reg_139 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal empty_fu_107_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal empty_reg_143 : STD_LOGIC_VECTOR (11 downto 0);
    signal empty_73_fu_111_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal empty_73_reg_148 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_v_mix_upsample_false_9_Pipeline_VITIS_LOOP_107_2_fu_98_ap_start : STD_LOGIC;
    signal grp_v_mix_upsample_false_9_Pipeline_VITIS_LOOP_107_2_fu_98_ap_done : STD_LOGIC;
    signal grp_v_mix_upsample_false_9_Pipeline_VITIS_LOOP_107_2_fu_98_ap_idle : STD_LOGIC;
    signal grp_v_mix_upsample_false_9_Pipeline_VITIS_LOOP_107_2_fu_98_ap_ready : STD_LOGIC;
    signal grp_v_mix_upsample_false_9_Pipeline_VITIS_LOOP_107_2_fu_98_srcLayer1Rgb_read : STD_LOGIC;
    signal grp_v_mix_upsample_false_9_Pipeline_VITIS_LOOP_107_2_fu_98_srcLayer1x_din : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_v_mix_upsample_false_9_Pipeline_VITIS_LOOP_107_2_fu_98_srcLayer1x_write : STD_LOGIC;
    signal grp_v_mix_upsample_false_9_Pipeline_VITIS_LOOP_107_2_fu_98_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln105_fu_123_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal y_fu_60 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    signal y_8_fu_128_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal HwReg_layerHeight_1_val_read_local : STD_LOGIC;
    signal HwReg_layerHeight_1_val_c_write_local : STD_LOGIC;
    signal HwReg_layerWidth_1_val_read_local : STD_LOGIC;
    signal HwReg_layerWidth_1_val_c_write_local : STD_LOGIC;
    signal HwReg_layerEnableFlag_1_val_read_local : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component main_design_v_mix_0_0_v_mix_upsample_false_9_Pipeline_VITIS_LOOP_107_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        srcLayer1Rgb_dout : IN STD_LOGIC_VECTOR (23 downto 0);
        srcLayer1Rgb_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        srcLayer1Rgb_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        srcLayer1Rgb_empty_n : IN STD_LOGIC;
        srcLayer1Rgb_read : OUT STD_LOGIC;
        srcLayer1x_din : OUT STD_LOGIC_VECTOR (23 downto 0);
        srcLayer1x_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        srcLayer1x_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        srcLayer1x_full_n : IN STD_LOGIC;
        srcLayer1x_write : OUT STD_LOGIC;
        empty : IN STD_LOGIC_VECTOR (11 downto 0) );
    end component;



begin
    grp_v_mix_upsample_false_9_Pipeline_VITIS_LOOP_107_2_fu_98 : component main_design_v_mix_0_0_v_mix_upsample_false_9_Pipeline_VITIS_LOOP_107_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_v_mix_upsample_false_9_Pipeline_VITIS_LOOP_107_2_fu_98_ap_start,
        ap_done => grp_v_mix_upsample_false_9_Pipeline_VITIS_LOOP_107_2_fu_98_ap_done,
        ap_idle => grp_v_mix_upsample_false_9_Pipeline_VITIS_LOOP_107_2_fu_98_ap_idle,
        ap_ready => grp_v_mix_upsample_false_9_Pipeline_VITIS_LOOP_107_2_fu_98_ap_ready,
        srcLayer1Rgb_dout => srcLayer1Rgb_dout,
        srcLayer1Rgb_num_data_valid => ap_const_lv3_0,
        srcLayer1Rgb_fifo_cap => ap_const_lv3_0,
        srcLayer1Rgb_empty_n => srcLayer1Rgb_empty_n,
        srcLayer1Rgb_read => grp_v_mix_upsample_false_9_Pipeline_VITIS_LOOP_107_2_fu_98_srcLayer1Rgb_read,
        srcLayer1x_din => grp_v_mix_upsample_false_9_Pipeline_VITIS_LOOP_107_2_fu_98_srcLayer1x_din,
        srcLayer1x_num_data_valid => ap_const_lv3_0,
        srcLayer1x_fifo_cap => ap_const_lv3_0,
        srcLayer1x_full_n => srcLayer1x_full_n,
        srcLayer1x_write => grp_v_mix_upsample_false_9_Pipeline_VITIS_LOOP_107_2_fu_98_srcLayer1x_write,
        empty => empty_73_reg_148);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and ((ap_const_lv1_0 = HwReg_layerEnableFlag_1_val_read_reg_139) or (icmp_ln105_fu_123_p2 = ap_const_lv1_1)))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_v_mix_upsample_false_9_Pipeline_VITIS_LOOP_107_2_fu_98_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_v_mix_upsample_false_9_Pipeline_VITIS_LOOP_107_2_fu_98_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln105_fu_123_p2 = ap_const_lv1_0) and (ap_const_lv1_1 = HwReg_layerEnableFlag_1_val_read_reg_139))) then 
                    grp_v_mix_upsample_false_9_Pipeline_VITIS_LOOP_107_2_fu_98_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_v_mix_upsample_false_9_Pipeline_VITIS_LOOP_107_2_fu_98_ap_ready = ap_const_logic_1)) then 
                    grp_v_mix_upsample_false_9_Pipeline_VITIS_LOOP_107_2_fu_98_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    y_fu_60_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_lv1_1 = HwReg_layerEnableFlag_1_val_read_read_fu_92_p2))) then 
                y_fu_60 <= ap_const_lv12_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln105_fu_123_p2 = ap_const_lv1_0) and (ap_const_lv1_1 = HwReg_layerEnableFlag_1_val_read_reg_139))) then 
                y_fu_60 <= y_8_fu_128_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                HwReg_layerEnableFlag_1_val_read_reg_139 <= HwReg_layerEnableFlag_1_val_dout;
                empty_73_reg_148 <= empty_73_fu_111_p1;
                empty_reg_143 <= empty_fu_107_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, HwReg_layerEnableFlag_1_val_read_reg_139, ap_block_state1, grp_v_mix_upsample_false_9_Pipeline_VITIS_LOOP_107_2_fu_98_ap_done, ap_CS_fsm_state2, icmp_ln105_fu_123_p2, ap_CS_fsm_state3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and ((ap_const_lv1_0 = HwReg_layerEnableFlag_1_val_read_reg_139) or (icmp_ln105_fu_123_p2 = ap_const_lv1_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_v_mix_upsample_false_9_Pipeline_VITIS_LOOP_107_2_fu_98_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;

    HwReg_layerEnableFlag_1_val_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, HwReg_layerEnableFlag_1_val_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            HwReg_layerEnableFlag_1_val_blk_n <= HwReg_layerEnableFlag_1_val_empty_n;
        else 
            HwReg_layerEnableFlag_1_val_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    HwReg_layerEnableFlag_1_val_read <= HwReg_layerEnableFlag_1_val_read_local;

    HwReg_layerEnableFlag_1_val_read_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            HwReg_layerEnableFlag_1_val_read_local <= ap_const_logic_1;
        else 
            HwReg_layerEnableFlag_1_val_read_local <= ap_const_logic_0;
        end if; 
    end process;

    HwReg_layerEnableFlag_1_val_read_read_fu_92_p2 <= HwReg_layerEnableFlag_1_val_dout;

    HwReg_layerHeight_1_val_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, HwReg_layerHeight_1_val_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            HwReg_layerHeight_1_val_blk_n <= HwReg_layerHeight_1_val_empty_n;
        else 
            HwReg_layerHeight_1_val_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    HwReg_layerHeight_1_val_c_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, HwReg_layerHeight_1_val_c_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            HwReg_layerHeight_1_val_c_blk_n <= HwReg_layerHeight_1_val_c_full_n;
        else 
            HwReg_layerHeight_1_val_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    HwReg_layerHeight_1_val_c_din <= HwReg_layerHeight_1_val_dout;
    HwReg_layerHeight_1_val_c_write <= HwReg_layerHeight_1_val_c_write_local;

    HwReg_layerHeight_1_val_c_write_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            HwReg_layerHeight_1_val_c_write_local <= ap_const_logic_1;
        else 
            HwReg_layerHeight_1_val_c_write_local <= ap_const_logic_0;
        end if; 
    end process;

    HwReg_layerHeight_1_val_read <= HwReg_layerHeight_1_val_read_local;

    HwReg_layerHeight_1_val_read_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            HwReg_layerHeight_1_val_read_local <= ap_const_logic_1;
        else 
            HwReg_layerHeight_1_val_read_local <= ap_const_logic_0;
        end if; 
    end process;


    HwReg_layerWidth_1_val_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, HwReg_layerWidth_1_val_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            HwReg_layerWidth_1_val_blk_n <= HwReg_layerWidth_1_val_empty_n;
        else 
            HwReg_layerWidth_1_val_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    HwReg_layerWidth_1_val_c_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, HwReg_layerWidth_1_val_c_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            HwReg_layerWidth_1_val_c_blk_n <= HwReg_layerWidth_1_val_c_full_n;
        else 
            HwReg_layerWidth_1_val_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    HwReg_layerWidth_1_val_c_din <= HwReg_layerWidth_1_val_dout;
    HwReg_layerWidth_1_val_c_write <= HwReg_layerWidth_1_val_c_write_local;

    HwReg_layerWidth_1_val_c_write_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            HwReg_layerWidth_1_val_c_write_local <= ap_const_logic_1;
        else 
            HwReg_layerWidth_1_val_c_write_local <= ap_const_logic_0;
        end if; 
    end process;

    HwReg_layerWidth_1_val_read <= HwReg_layerWidth_1_val_read_local;

    HwReg_layerWidth_1_val_read_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            HwReg_layerWidth_1_val_read_local <= ap_const_logic_1;
        else 
            HwReg_layerWidth_1_val_read_local <= ap_const_logic_0;
        end if; 
    end process;

    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_v_mix_upsample_false_9_Pipeline_VITIS_LOOP_107_2_fu_98_ap_done)
    begin
        if ((grp_v_mix_upsample_false_9_Pipeline_VITIS_LOOP_107_2_fu_98_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, HwReg_layerHeight_1_val_empty_n, HwReg_layerWidth_1_val_empty_n, HwReg_layerEnableFlag_1_val_empty_n, HwReg_layerWidth_1_val_c_full_n, HwReg_layerHeight_1_val_c_full_n)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (ap_const_logic_0 = HwReg_layerHeight_1_val_c_full_n) or (ap_const_logic_0 = HwReg_layerWidth_1_val_c_full_n) or (ap_const_logic_0 = HwReg_layerEnableFlag_1_val_empty_n) or (ap_const_logic_0 = HwReg_layerWidth_1_val_empty_n) or (ap_const_logic_0 = HwReg_layerHeight_1_val_empty_n) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, HwReg_layerEnableFlag_1_val_read_reg_139, ap_CS_fsm_state2, icmp_ln105_fu_123_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and ((ap_const_lv1_0 = HwReg_layerEnableFlag_1_val_read_reg_139) or (icmp_ln105_fu_123_p2 = ap_const_lv1_1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(HwReg_layerEnableFlag_1_val_read_reg_139, ap_CS_fsm_state2, icmp_ln105_fu_123_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and ((ap_const_lv1_0 = HwReg_layerEnableFlag_1_val_read_reg_139) or (icmp_ln105_fu_123_p2 = ap_const_lv1_1)))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    empty_73_fu_111_p1 <= HwReg_layerWidth_1_val_dout(12 - 1 downto 0);
    empty_fu_107_p1 <= HwReg_layerHeight_1_val_dout(12 - 1 downto 0);
    grp_v_mix_upsample_false_9_Pipeline_VITIS_LOOP_107_2_fu_98_ap_start <= grp_v_mix_upsample_false_9_Pipeline_VITIS_LOOP_107_2_fu_98_ap_start_reg;
    icmp_ln105_fu_123_p2 <= "1" when (y_fu_60 = empty_reg_143) else "0";

    srcLayer1Rgb_read_assign_proc : process(grp_v_mix_upsample_false_9_Pipeline_VITIS_LOOP_107_2_fu_98_srcLayer1Rgb_read, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            srcLayer1Rgb_read <= grp_v_mix_upsample_false_9_Pipeline_VITIS_LOOP_107_2_fu_98_srcLayer1Rgb_read;
        else 
            srcLayer1Rgb_read <= ap_const_logic_0;
        end if; 
    end process;

    srcLayer1x_din <= grp_v_mix_upsample_false_9_Pipeline_VITIS_LOOP_107_2_fu_98_srcLayer1x_din;

    srcLayer1x_write_assign_proc : process(grp_v_mix_upsample_false_9_Pipeline_VITIS_LOOP_107_2_fu_98_srcLayer1x_write, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            srcLayer1x_write <= grp_v_mix_upsample_false_9_Pipeline_VITIS_LOOP_107_2_fu_98_srcLayer1x_write;
        else 
            srcLayer1x_write <= ap_const_logic_0;
        end if; 
    end process;

    y_8_fu_128_p2 <= std_logic_vector(unsigned(y_fu_60) + unsigned(ap_const_lv12_1));
end behav;
