<AutoPilot:project xmlns:AutoPilot="com.autoesl.autopilot.project" projectType="C/C++" top="v_mix" name="prj" ideType="classic">
    <solutions>
        <solution name="sol" status=""/>
    </solutions>
    <files>
        <file name="../../ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src/hls/hls_video_undistort.h" sc="0" tb="false" cflags="-I/home/nothon/fpga2C/ZTurnV2/ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src/hls -I/home/nothon/fpga2C/ZTurnV2/ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src" csimflags="" blackbox="false"/>
        <file name="../../ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src/hls/hls_video_types.h" sc="0" tb="false" cflags="-I/home/nothon/fpga2C/ZTurnV2/ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src/hls -I/home/nothon/fpga2C/ZTurnV2/ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src" csimflags="" blackbox="false"/>
        <file name="../../ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src/hls/hls_video_stereobm.h" sc="0" tb="false" cflags="-I/home/nothon/fpga2C/ZTurnV2/ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src/hls -I/home/nothon/fpga2C/ZTurnV2/ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src" csimflags="" blackbox="false"/>
        <file name="../../ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src/hls/hls_video_mem.h" sc="0" tb="false" cflags="-I/home/nothon/fpga2C/ZTurnV2/ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src/hls -I/home/nothon/fpga2C/ZTurnV2/ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src" csimflags="" blackbox="false"/>
        <file name="../../ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src/hls/hls_video_io.h" sc="0" tb="false" cflags="-I/home/nothon/fpga2C/ZTurnV2/ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src/hls -I/home/nothon/fpga2C/ZTurnV2/ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src" csimflags="" blackbox="false"/>
        <file name="../../ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src/hls/hls_video_imgproc.h" sc="0" tb="false" cflags="-I/home/nothon/fpga2C/ZTurnV2/ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src/hls -I/home/nothon/fpga2C/ZTurnV2/ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src" csimflags="" blackbox="false"/>
        <file name="../../ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src/hls/hls_video_imgbase.h" sc="0" tb="false" cflags="-I/home/nothon/fpga2C/ZTurnV2/ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src/hls -I/home/nothon/fpga2C/ZTurnV2/ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src" csimflags="" blackbox="false"/>
        <file name="../../ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src/hls/hls_video_hough.h" sc="0" tb="false" cflags="-I/home/nothon/fpga2C/ZTurnV2/ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src/hls -I/home/nothon/fpga2C/ZTurnV2/ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src" csimflags="" blackbox="false"/>
        <file name="../../ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src/hls/hls_video_histogram.h" sc="0" tb="false" cflags="-I/home/nothon/fpga2C/ZTurnV2/ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src/hls -I/home/nothon/fpga2C/ZTurnV2/ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src" csimflags="" blackbox="false"/>
        <file name="../../ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src/hls/hls_video_harris.h" sc="0" tb="false" cflags="-I/home/nothon/fpga2C/ZTurnV2/ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src/hls -I/home/nothon/fpga2C/ZTurnV2/ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src" csimflags="" blackbox="false"/>
        <file name="../../ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src/hls/hls_video_haar.h" sc="0" tb="false" cflags="-I/home/nothon/fpga2C/ZTurnV2/ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src/hls -I/home/nothon/fpga2C/ZTurnV2/ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src" csimflags="" blackbox="false"/>
        <file name="../../ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src/hls/hls_video_fast.h" sc="0" tb="false" cflags="-I/home/nothon/fpga2C/ZTurnV2/ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src/hls -I/home/nothon/fpga2C/ZTurnV2/ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src" csimflags="" blackbox="false"/>
        <file name="../../ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src/hls/hls_video_core.h" sc="0" tb="false" cflags="-I/home/nothon/fpga2C/ZTurnV2/ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src/hls -I/home/nothon/fpga2C/ZTurnV2/ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src" csimflags="" blackbox="false"/>
        <file name="../../ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src/hls/hls_video_arithm.h" sc="0" tb="false" cflags="-I/home/nothon/fpga2C/ZTurnV2/ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src/hls -I/home/nothon/fpga2C/ZTurnV2/ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src" csimflags="" blackbox="false"/>
        <file name="../../ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src/hls/hls_axi_io.h" sc="0" tb="false" cflags="-I/home/nothon/fpga2C/ZTurnV2/ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src/hls -I/home/nothon/fpga2C/ZTurnV2/ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src" csimflags="" blackbox="false"/>
        <file name="../../ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src/hls_opencv.h" sc="0" tb="false" cflags="-I/home/nothon/fpga2C/ZTurnV2/ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src/hls -I/home/nothon/fpga2C/ZTurnV2/ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src" csimflags="" blackbox="false"/>
        <file name="../../ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src/hls_video.h" sc="0" tb="false" cflags="-I/home/nothon/fpga2C/ZTurnV2/ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src/hls -I/home/nothon/fpga2C/ZTurnV2/ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src" csimflags="" blackbox="false"/>
        <file name="../../ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src/v_csc.h" sc="0" tb="false" cflags="-I/home/nothon/fpga2C/ZTurnV2/ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src/hls -I/home/nothon/fpga2C/ZTurnV2/ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src" csimflags="" blackbox="false"/>
        <file name="../../ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src/v_csc.cpp" sc="0" tb="false" cflags="-I/home/nothon/fpga2C/ZTurnV2/ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src/hls -I/home/nothon/fpga2C/ZTurnV2/ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src" csimflags="" blackbox="false"/>
        <file name="../../ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src/v_dma.h" sc="0" tb="false" cflags="-I/home/nothon/fpga2C/ZTurnV2/ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src/hls -I/home/nothon/fpga2C/ZTurnV2/ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src" csimflags="" blackbox="false"/>
        <file name="../../ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src/v_dma.cpp" sc="0" tb="false" cflags="-I/home/nothon/fpga2C/ZTurnV2/ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src/hls -I/home/nothon/fpga2C/ZTurnV2/ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src" csimflags="" blackbox="false"/>
        <file name="../../ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src/v_mix.h" sc="0" tb="false" cflags="-I/home/nothon/fpga2C/ZTurnV2/ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src/hls -I/home/nothon/fpga2C/ZTurnV2/ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src" csimflags="" blackbox="false"/>
        <file name="../../ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src/v_mix.cpp" sc="0" tb="false" cflags="-I/home/nothon/fpga2C/ZTurnV2/ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src/hls -I/home/nothon/fpga2C/ZTurnV2/ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src" csimflags="" blackbox="false"/>
        <file name="../../ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src/v_mix_config.h" sc="0" tb="false" cflags="-I/home/nothon/fpga2C/ZTurnV2/ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src/hls -I/home/nothon/fpga2C/ZTurnV2/ZTurnV2.gen/sources_1/bd/main_design/ip/main_design_v_mix_0_0/src" csimflags="" blackbox="false"/>
    </files>
</AutoPilot:project>

