#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Jul 15 10:02:34 CEST 2024
# SW Build 5076996 on Wed May 22 18:36:09 MDT 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_ctrl_axi_behav -key {Behavioral:sim_1:Functional:tb_ctrl_axi} -tclbatch tb_ctrl_axi.tcl -protoinst "protoinst_files/verif_design.protoinst" -view /home/nothon/fpga2C/ip_repo/noip_ctrl/tb_ctrl_behav.wcfg -log simulate.log"
xsim tb_ctrl_axi_behav -key {Behavioral:sim_1:Functional:tb_ctrl_axi} -tclbatch tb_ctrl_axi.tcl -protoinst "protoinst_files/verif_design.protoinst" -view /home/nothon/fpga2C/ip_repo/noip_ctrl/tb_ctrl_behav.wcfg -log simulate.log

